In [1]:
import numpy as np
import pandas as pd

In [2]:
obj= pd.Series(range(4), index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [4]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [5]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [7]:
df.sort_index(axis=1)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [8]:
df.sort_index(axis=1, inplace=True)

In [9]:
df

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [10]:
df.sort_index(ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008

In [11]:
df.sort_index(axis=1,ascending=False)

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
0,2008,jtezu11f88k007763,clean vehicle,new jersey,6300,cruiser,274117,159348797,usa,10 days left,black,toyota
1,2011,2fmdk3gc4bbb02217,clean vehicle,tennessee,2899,se,190552,166951262,usa,6 days left,silver,ford
2,2018,3c4pdcgg5jt346413,clean vehicle,georgia,5350,mpv,39590,167655728,usa,2 days left,silver,dodge
3,2014,1ftfw1et4efc23745,clean vehicle,virginia,25000,door,64146,167753855,usa,22 hours left,blue,ford
4,2018,3gcpcrec2jg473991,clean vehicle,florida,27700,1500,6654,167763266,usa,22 hours left,red,chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2019,3n1cn7ap9kl880319,clean vehicle,california,7800,versa,23609,167722715,usa,1 days left,red,nissan
2495,2018,3n1cn7ap5jl884088,clean vehicle,florida,9200,versa,34553,167762225,usa,21 hours left,silver,nissan
2496,2018,3n1cn7ap9jl884191,clean vehicle,florida,9200,versa,31594,167762226,usa,21 hours left,silver,nissan
2497,2018,3n1cn7ap3jl883263,clean vehicle,florida,9200,versa,32557,167762227,usa,2 days left,black,nissan
2498,2018,3n1cn7ap4jl884311,clean vehicle,florida,9200,versa,31371,167762228,usa,21 hours left,silver,nissan

In [12]:
df.sort_values(by='price')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
530,chevrolet,gray,17 hours left,usa,167650636,194673,door,0,texas,salvage insurance,1gndt13s632267445,2003
522,ford,red,17 hours left,usa,167357813,145483,door,0,oklahoma,salvage insurance,1fmcu03128kc80487,2008
516,peterbilt,blue,17 hours left,usa,167529788,982486,truck,0,florida,salvage insurance,1xp7d49x09d784257,2009
514,lincoln,green,17 hours left,usa,167154617,89705,door,0,minnesota,salvage insurance,1lnhm87a25y619997,2005
351,chevrolet,gray,19 hours left,usa,167650796,159266,door,0,california,salvage insurance,2g1wb58kx81220813,2008
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017

In [13]:
df.sort_values(by=['price', 'year'], ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
330,ford,green,19 hours left,usa,167359712,296860,door,0,california,salvage insurance,1falp62w5th144314,1996
496,ford,red,17 hours left,usa,167357804,252588,pickup,0,oklahoma,salvage insurance,1ftef15n0tlc14455,1996
410,chevrolet,green,2 days left,usa,167425634,274706,door,0,arizona,salvage insurance,2gcec19h8s1195266,1995
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993

In [15]:
df['rating'] = df['price'].rank(method="max")

In [18]:
df.sort_values('price')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year,rating
530,chevrolet,gray,17 hours left,usa,167650636,194673,door,0,texas,salvage insurance,1gndt13s632267445,2003,43.0
522,ford,red,17 hours left,usa,167357813,145483,door,0,oklahoma,salvage insurance,1fmcu03128kc80487,2008,43.0
516,peterbilt,blue,17 hours left,usa,167529788,982486,truck,0,florida,salvage insurance,1xp7d49x09d784257,2009,43.0
514,lincoln,green,17 hours left,usa,167154617,89705,door,0,minnesota,salvage insurance,1lnhm87a25y619997,2005,43.0
351,chevrolet,gray,19 hours left,usa,167650796,159266,door,0,california,salvage insurance,2g1wb58kx81220813,2008,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019,2495.0
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019,2496.0
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019,2497.0
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019,2498.0
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017,2499.0