In [2]:
import pandas as pd
import numpy as np

In [2]:

df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/uzbekistan.csv', index_col=0)
df.columns = ['maydoni','aholisi']
df

                                maydoni    aholisi
Boʻlinishi
Andijon viloyati                 4200.0  1899000.0
Buxoro viloyati                 39400.0  1384700.0
Fargʻona viloyati                6800.0  2597000.0
Jizzax viloyati                 20500.0   910500.0
Xorazm viloyati                  6300.0  1200000.0
Namangan viloyati                7900.0  1862000.0
Navoiy viloyati                110800.0   767500.0
Qashqadaryo viloyati            28400.0  2029000.0
Qoraqalpogʻiston Respublikasi  160000.0  1200000.0
Samarqand viloyati              16400.0  2322000.0
Sirdaryo viloyati                5100.0   648100.0
Surxondaryo viloyati            20800.0  1676000.0
Toshkent viloyati               15300.0  4450000.0

In [4]:
df.sum()

maydoni      441900.0
aholisi    22945800.0
dtype: float64

In [5]:
df2 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/gm_sales.csv", index_col=0)
df2.head()

         2020   2021
Labo     4521   7542
Damas   30889  33682
Spark   16370   6485
Nexia   41663  14442
Cobalt  44901  36317

In [13]:
df2.sum()

2020    168712
2021    124734
dtype: int64

In [7]:
df2.sum(axis=1)

Labo      12063
Damas     64571
Spark     22855
Nexia     56105
Cobalt    81218
Gentra    56634
dtype: int64

In [9]:
df2.mean(axis=1)

Labo       6031.5
Damas     32285.5
Spark     11427.5
Nexia     28052.5
Cobalt    40609.0
Gentra    28317.0
dtype: float64

In [10]:
df

                                maydoni    aholisi
Boʻlinishi
Andijon viloyati                 4200.0  1899000.0
Buxoro viloyati                 39400.0  1384700.0
Fargʻona viloyati                6800.0  2597000.0
Jizzax viloyati                 20500.0   910500.0
Xorazm viloyati                  6300.0  1200000.0
Namangan viloyati                7900.0  1862000.0
Navoiy viloyati                110800.0   767500.0
Qashqadaryo viloyati            28400.0  2029000.0
Qoraqalpogʻiston Respublikasi  160000.0  1200000.0
Samarqand viloyati              16400.0  2322000.0
Sirdaryo viloyati                5100.0   648100.0
Surxondaryo viloyati            20800.0  1676000.0
Toshkent viloyati               15300.0  4450000.0

In [12]:
df.mean()

maydoni    3.399231e+04
aholisi    1.765062e+06
dtype: float64

In [14]:
df.idxmax()

maydoni    Qoraqalpogʻiston Respublikasi
aholisi                Toshkent viloyati
dtype: str

In [15]:
df.idxmin()

maydoni     Andijon viloyati
aholisi    Sirdaryo viloyati
dtype: str

In [16]:
df

                                maydoni    aholisi
Boʻlinishi
Andijon viloyati                 4200.0  1899000.0
Buxoro viloyati                 39400.0  1384700.0
Fargʻona viloyati                6800.0  2597000.0
Jizzax viloyati                 20500.0   910500.0
Xorazm viloyati                  6300.0  1200000.0
Namangan viloyati                7900.0  1862000.0
Navoiy viloyati                110800.0   767500.0
Qashqadaryo viloyati            28400.0  2029000.0
Qoraqalpogʻiston Respublikasi  160000.0  1200000.0
Samarqand viloyati              16400.0  2322000.0
Sirdaryo viloyati                5100.0   648100.0
Surxondaryo viloyati            20800.0  1676000.0
Toshkent viloyati               15300.0  4450000.0

In [17]:
df['aholisi'].argmax()

np.int64(12)

In [19]:
df.iloc[12]

maydoni      15300.0
aholisi    4450000.0
Name: Toshkent viloyati, dtype: float64

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0