In [1]:
import pandas as pd

In [2]:
data = {
    'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
}
df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [3]:
df.head()

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [4]:
df.head(3)

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56

In [6]:
df.shape

(8, 3)

In [7]:
df = pd.DataFrame(data, columns=["Yil", "Temp", "Aholi soni"])
df.head()

    Yil  Temp  Aholi soni
0  2021  1.54        33.9
1  2020  1.48        33.5
2  2019  1.56        32.9
3  2018  1.62        32.5
4  2017  1.65        31.9

In [8]:
df = pd.DataFrame(data, columns=["Yil", "Temp", "Aholi soni","YAIM"])
df.head()

    Yil  Temp  Aholi soni YAIM
0  2021  1.54        33.9  NaN
1  2020  1.48        33.5  NaN
2  2019  1.56        32.9  NaN
3  2018  1.62        32.5  NaN
4  2017  1.65        31.9  NaN

In [10]:
df = pd.DataFrame(data, columns=["Yil", "Temp", "Aholi soni","YAIM"], index=["first","two", 25, 10, 15,16,45, 00])
df

        Yil  Temp  Aholi soni YAIM
first  2021  1.54        33.9  NaN
two    2020  1.48        33.5  NaN
25     2019  1.56        32.9  NaN
10     2018  1.62        32.5  NaN
15     2017  1.65        31.9  NaN
16     2016  1.66        31.4  NaN
45     2015  1.64        30.9  NaN
0      2010  1.53        28.5  NaN

In [11]:
df['Aholi soni']

first    33.9
two      33.5
25       32.9
10       32.5
15       31.9
16       31.4
45       30.9
0        28.5
Name: Aholi soni, dtype: float64

In [12]:
df.Temp

first    1.54
two      1.48
25       1.56
10       1.62
15       1.65
16       1.66
45       1.64
0        1.53
Name: Temp, dtype: float64

In [13]:
df.YAIM =0
df

        Yil  Temp  Aholi soni  YAIM
first  2021  1.54        33.9     0
two    2020  1.48        33.5     0
25     2019  1.56        32.9     0
10     2018  1.62        32.5     0
15     2017  1.65        31.9     0
16     2016  1.66        31.4     0
45     2015  1.64        30.9     0
0      2010  1.53        28.5     0

In [14]:
val = pd.Series([1700,1250,600], index = ["two", 16,0])
df.YAIM = val

In [15]:
df

        Yil  Temp  Aholi soni    YAIM
first  2021  1.54        33.9     NaN
two    2020  1.48        33.5  1700.0
25     2019  1.56        32.9     NaN
10     2018  1.62        32.5     NaN
15     2017  1.65        31.9     NaN
16     2016  1.66        31.4  1250.0
45     2015  1.64        30.9     NaN
0      2010  1.53        28.5   600.0

In [16]:
val = [1200,2500,4581,25630,154548,21650,654,4800]
df.YAIM = val
df

        Yil  Temp  Aholi soni    YAIM
first  2021  1.54        33.9    1200
two    2020  1.48        33.5    2500
25     2019  1.56        32.9    4581
10     2018  1.62        32.5   25630
15     2017  1.65        31.9  154548
16     2016  1.66        31.4   21650
45     2015  1.64        30.9     654
0      2010  1.53        28.5    4800

In [17]:
df["1500+"] = df.YAIM > 1500
df

        Yil  Temp  Aholi soni    YAIM  1500+
first  2021  1.54        33.9    1200  False
two    2020  1.48        33.5    2500   True
25     2019  1.56        32.9    4581   True
10     2018  1.62        32.5   25630   True
15     2017  1.65        31.9  154548   True
16     2016  1.66        31.4   21650   True
45     2015  1.64        30.9     654  False
0      2010  1.53        28.5    4800   True

In [18]:
del df["1500+"]
df

        Yil  Temp  Aholi soni    YAIM
first  2021  1.54        33.9    1200
two    2020  1.48        33.5    2500
25     2019  1.56        32.9    4581
10     2018  1.62        32.5   25630
15     2017  1.65        31.9  154548
16     2016  1.66        31.4   21650
45     2015  1.64        30.9     654
0      2010  1.53        28.5    4800

In [20]:
data = {
    'Uzbekistan': {2021: 33.9, 2020: 33.5, 2019: 32.9, 2018: 32.5, 2017: 31.9},
    'Kazakhstan': {2021: 18.9, 2020: 18.7, 2019: 18.5, 2018: 18.3, 2017: 18.1, 2016: 17.8}
}
df2 = pd.DataFrame(data)
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [21]:
df2.index.name = "Yil"
df2

      Uzbekistan  Kazakhstan
Yil
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [22]:
df2 = pd.DataFrame(data, index=[2019,2016,2021])
df2

      Uzbekistan  Kazakhstan
2019        32.9        18.5
2016         NaN        17.8
2021        33.9        18.9

In [23]:
df2.T

            2019  2016  2021
Uzbekistan  32.9   NaN  33.9
Kazakhstan  18.5  17.8  18.9

In [26]:
arr=df2.values

In [27]:
arr

array([[32.9, 18.5],
       [ nan, 17.8],
       [33.9, 18.9]])

In [28]:
type(arr)

numpy.ndarray

In [29]:
df

        Yil  Temp  Aholi soni    YAIM
first  2021  1.54        33.9    1200
two    2020  1.48        33.5    2500
25     2019  1.56        32.9    4581
10     2018  1.62        32.5   25630
15     2017  1.65        31.9  154548
16     2016  1.66        31.4   21650
45     2015  1.64        30.9     654
0      2010  1.53        28.5    4800

In [30]:
df.index

Index(['first', 'two', 25, 10, 15, 16, 45, 0], dtype='object')

In [31]:
df.columns

Index(['Yil', 'Temp', 'Aholi soni', 'YAIM'], dtype='str')

In [33]:
indeks = df.columns

In [34]:
indeks

Index(['Yil', 'Temp', 'Aholi soni', 'YAIM'], dtype='str')

In [35]:
"Temp" in indeks

True

In [36]:
df2

      Uzbekistan  Kazakhstan
2019        32.9        18.5
2016         NaN        17.8
2021        33.9        18.9

In [37]:
"Tajikistan" in df2

False

In [38]:
2021 in df2.index

True

In [39]:
indeks

Index(['Yil', 'Temp', 'Aholi soni', 'YAIM'], dtype='str')

In [40]:
indeks[0]

'Yil'

In [41]:
indeks[2:4]

Index(['Aholi soni', 'YAIM'], dtype='str')

In [ ]:
indeks[0] = "qiymat" # index qiymatini o'zgartirib bo'lmaydi

TypeError: Index does not support mutable operations

In [43]:
data1 = {
    'Uzbekistan': {2021: 33.9, 2020: 33.5, 2019: 32.9, 2018: 32.5, 2017: 31.9},
    'Kazakhstan': {2021: 18.9, 2020: 18.7, 2019: 18.5, 2018: 18.3, 2017: 18.1, 2016: 17.8}
}
df = pd.DataFrame(data1)
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [44]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455", "javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com", "javohir":"javohir445@gmail.com"}

data = {
    'username': usernames,
    'email': emails
}

df = pd.DataFrame(data)
df

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com

In [45]:
df.index

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='str')

In [46]:
arr = ['anvar', 'olim', 'maryam', 'javohir']
arr[0]

'anvar'

In [47]:
data2 = {
    'username': {"olim": "olimjon21", "maryam": "maryam2020"},
    'email': {"olim": "olimjon21@mail.ru", "maryam": "maryam20@gmail.com"}
}

In [ ]:
df2 = df.append(pd.DataFrame(data2))  # bu usul eskiribdi , demak endi ishlamaydi

AttributeError: 'DataFrame' object has no attribute 'append'

In [49]:
df2 = pd.concat([df, pd.DataFrame(data2)])

In [50]:
df2

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [57]:
newind = pd.Index(["olim", "Nafisa", "Hamida"])
newind

Index(['olim', 'Nafisa', 'Hamida'], dtype='str')

In [58]:
newind.isin(df2.index)

array([ True, False, False])

In [59]:
df2.index.difference(newind)

Index(['anvar', 'javohir', 'maryam'], dtype='str')

In [60]:
newind.difference(df2.index)

Index(['Hamida', 'Nafisa'], dtype='str')

#### Union jamlab berarkan

In [61]:
df2.index.union(newind)

Index(['Hamida', 'Nafisa', 'anvar', 'javohir', 'maryam', 'maryam', 'olim',
       'olim'],
      dtype='str')

In [62]:
newind.union(df2.index)

Index(['Hamida', 'Nafisa', 'anvar', 'javohir', 'maryam', 'maryam', 'olim',
       'olim'],
      dtype='str')

In [63]:
df2.index.delete(0)

Index(['olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='str')

In [64]:
newind

Index(['olim', 'Nafisa', 'Hamida'], dtype='str')

In [65]:
newind.drop("Hamida")

Index(['olim', 'Nafisa'], dtype='str')