In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik': [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}

df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [3]:
data= df["Aholi soni"]
data

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [9]:
data= df[["Aholi soni"]]
data

   Aholi soni
0        33.9
1        33.5
2        32.9
3        32.5
4        31.9
5        31.4
6        30.9
7        28.5

In [12]:
data= df["Aholi soni"]
data

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [13]:
type(data[0])

numpy.float64

In [14]:
type(data[[0]])

pandas.Series

In [15]:
data

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [16]:
data[0:4]

0    33.9
1    33.5
2    32.9
3    32.5
Name: Aholi soni, dtype: float64

In [17]:
data[[2,4,7]]

2    32.9
4    31.9
7    28.5
Name: Aholi soni, dtype: float64

In [18]:
obj = pd.Series(np.arange(8), index = ['a', 'b', 'c', 'd','e','f','g','h'])
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj['a']  #qiymat ko'rinishida

np.int64(0)

In [ ]:
obj[['a']]  #ro'yxat ya'ni series ko'rinishida

a    0
dtype: int64

In [21]:
obj[0:4]

a    0
b    1
c    2
d    3
dtype: int64

In [ ]:
obj['a': 'f'] #lekin bunda f qiymat ham kiradi

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64

In [23]:
obj['c': 'h']

c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [26]:
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj[[1,5]] # bu usul ishlamadi

KeyError: "None of [Index([1, 5], dtype='int64')] are in the [index]"

In [ ]:
obj.iloc[[1,5]]  # bu yangicha usul ekan

b    1
f    5
dtype: int64

In [34]:
obj[['a', 'g']]

a    0
g    6
dtype: int64

In [35]:
obj['a':'c']

a    0
b    1
c    2
dtype: int64

In [36]:
obj['a':'c']=10

In [37]:
obj

a    10
b    10
c    10
d     3
e     4
f     5
g     6
h     7
dtype: int64

In [39]:
obj[obj<10]

d    3
e    4
f    5
g    6
h    7
dtype: int64

### Elementlarni tanlash , DataFrame

In [40]:
uz = {2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9, 2016:31.4, 2015:30.9}
kz = {2020:18.8, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8, 2015:17.6}
tj = {2020:9.5, 2019:9.3, 2018:9.1, 2017:8.9, 2016:8.7, 2015:8.5}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.2, 2016:6.1, 2015:6.0}
tr = {2020:6.0, 2019:5.9, 2018:5.9, 2017:5.8, 2016:5.6, 2015:5.6}

df = pd.DataFrame({
    'Uzbekistan': uz,
    'Kazakhstan': kz,
    'Tajikistan': tj,
    'Kyrgyzstan': kg,
    'Turkmenistan': tr
})

print(df)

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [41]:
df['Uzbekistan']

2020    33.5
2019    32.9
2018    32.5
2017    31.9
2016    31.4
2015    30.9
Name: Uzbekistan, dtype: float64

In [42]:
df[['Uzbekistan']]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [43]:
df['Uzbekistan'].to_numpy()

array([33.5, 32.9, 32.5, 31.9, 31.4, 30.9])

In [44]:
df[['Uzbekistan','Turkmenistan']]

      Uzbekistan  Turkmenistan
2020        33.5           6.0
2019        32.9           5.9
2018        32.5           5.9
2017        31.9           5.8
2016        31.4           5.6
2015        30.9           5.6

In [45]:
df[3:]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [46]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [47]:
df>10

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        True        True       False       False         False
2019        True        True       False       False         False
2018        True        True       False       False         False
2017        True        True       False       False         False
2016        True        True       False       False         False
2015        True        True       False       False         False

In [48]:
df[['Uzbekistan']][df['Uzbekistan'] >32]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5

In [50]:
dfuz = df[['Uzbekistan']]
dfuz

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [51]:
dfuz[dfuz['Uzbekistan']>32]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5

In [52]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [54]:
df2 = df.transpose().copy()
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgyzstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [55]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [56]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgyzstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [59]:
df2[df2[2015]>6]

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan  18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan   9.5   9.3   9.1   8.9   8.7   8.5

### .loc va .iloc

In [60]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [61]:
df[['Kazakhstan']]

      Kazakhstan
2020        18.8
2019        18.5
2018        18.3
2017        18.1
2016        17.8
2015        17.6

In [62]:
df.loc[[2017]]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2017        31.9        18.1         8.9         6.2           5.8

In [63]:
df.loc[2017]

Uzbekistan      31.9
Kazakhstan      18.1
Tajikistan       8.9
Kyrgyzstan       6.2
Turkmenistan     5.8
Name: 2017, dtype: float64

In [65]:
df.loc[[2015, 2017],["Uzbekistan", "Tajikistan"]]

      Uzbekistan  Tajikistan
2015        30.9         8.5
2017        31.9         8.9

In [66]:
df.iloc[[0,4]]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2016        31.4        17.8         8.7         6.1           5.6

In [71]:
df.iloc[[0,4],[0,4,3]]

      Uzbekistan  Turkmenistan  Kyrgyzstan
2020        33.5           6.0         6.5
2016        31.4           5.6         6.1

In [72]:
df.at[2015, "Uzbekistan"]

np.float64(30.9)

In [73]:
df.iat[2,4]

np.float64(5.9)