In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [10]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'), index=['Olma','Anor','Uzum'])
df2 = pd.DataFrame(np.arange(12).reshape(4,3), columns=list('abc'), index=['Olma','Anor','Qovun','Anjir'])

In [11]:
df1

      b  c  d
Olma  0  1  2
Anor  3  4  5
Uzum  6  7  8

In [12]:
df2

       a   b   c
Olma   0   1   2
Anor   3   4   5
Qovun  6   7   8
Anjir  9  10  11

In [13]:
df1 + df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [14]:
df1.add(df2, fill_value=0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [15]:
df2.add(df1, fill_value=0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [ ]:
df2.sub(df1, fill_value=0) #ayirish

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [17]:
df1.rsub(df2, fill_value=0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [18]:
df2.div(df1) # bo'lish

        a         b     c   d
Anjir NaN       NaN   NaN NaN
Anor  NaN  1.333333  1.25 NaN
Olma  NaN       inf  2.00 NaN
Qovun NaN       NaN   NaN NaN
Uzum  NaN       NaN   NaN NaN

In [19]:
df2.rdiv(df1) #teskari bo'lish

        a     b    c   d
Anjir NaN   NaN  NaN NaN
Anor  NaN  0.75  0.8 NaN
Olma  NaN  0.00  0.5 NaN
Qovun NaN   NaN  NaN NaN
Uzum  NaN   NaN  NaN NaN

### ```DF``` va ```Series``` o'rtasida arifmetik amallar

In [20]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
obj = pd.Series([1,1,2,2], index=df.columns)

In [21]:
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [22]:
obj

Olma     1
Anor     1
Qovun    2
Anjir    2
dtype: int64

In [23]:
df + obj

   Olma  Anor  Qovun  Anjir
a     2     3      5      6
b     6     7      9     10
c    10    11     13     14

In [24]:
obj = pd.Series([2,3,1], index=['Olma','Uzum','Qovun'])

In [25]:
df.sub(obj)

   Anjir  Anor  Olma  Qovun  Uzum
a    NaN   NaN  -1.0    2.0   NaN
b    NaN   NaN   3.0    6.0   NaN
c    NaN   NaN   7.0   10.0   NaN

In [27]:
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [28]:
obj

Olma     2
Uzum     3
Qovun    1
dtype: int64

In [26]:
df + obj["Olma"]

   Olma  Anor  Qovun  Anjir
a     3     4      5      6
b     7     8      9     10
c    11    12     13     14