In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame(np.random.randn(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

       Olma      Anor     Qovun     Anjir
a -1.213396  0.331102 -0.129994 -0.147908
b  1.469557 -1.397087  1.184603  0.634715
c  1.319551 -0.927369  0.140952 -0.660071

In [4]:
np.abs(df)

       Olma      Anor     Qovun     Anjir
a  1.213396  0.331102  0.129994  0.147908
b  1.469557  1.397087  1.184603  0.634715
c  1.319551  0.927369  0.140952  0.660071

In [5]:
np.round(df)

   Olma  Anor  Qovun  Anjir
a  -1.0   0.0   -0.0   -0.0
b   1.0  -1.0    1.0    1.0
c   1.0  -1.0    0.0   -1.0

In [6]:
df

       Olma      Anor     Qovun     Anjir
a -1.213396  0.331102 -0.129994 -0.147908
b  1.469557 -1.397087  1.184603  0.634715
c  1.319551 -0.927369  0.140952 -0.660071

In [7]:
df.mean()

Olma     0.525237
Anor    -0.664451
Qovun    0.398520
Anjir   -0.057755
dtype: float64

In [8]:
df.mean(axis=1)

a   -0.290049
b    0.472947
c   -0.031734
dtype: float64

In [9]:
df.apply(np.abs)

       Olma      Anor     Qovun     Anjir
a  1.213396  0.331102  0.129994  0.147908
b  1.469557  1.397087  1.184603  0.634715
c  1.319551  0.927369  0.140952  0.660071

In [10]:
df.apply(sum)

Olma     1.575712
Anor    -1.993354
Qovun    1.195561
Anjir   -0.173264
dtype: float64

In [11]:
df.apply(sum, axis=1)

a   -1.160196
b    1.891789
c   -0.126938
dtype: float64

In [12]:
f = lambda x : x.max() - x.min()

In [13]:
df.apply(f)

Olma     2.682954
Anor     1.728189
Qovun    1.314597
Anjir    1.294786
dtype: float64

In [16]:
def foo(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [17]:
df.apply(foo)

         Olma      Anor     Qovun     Anjir
min -1.213396 -1.397087 -0.129994 -0.660071
max  1.469557  0.331102  1.184603  0.634715

In [18]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [ ]:
df.applymap(lambda x: x*x)#bu eskiribdi o'rniga shunchaki map

AttributeError: 'DataFrame' object has no attribute 'applymap'

In [23]:
df.map(lambda x: x*x)

   Olma  Anor  Qovun  Anjir
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144