![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **1-QISM**

In [1]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)
df

               country     density   densityMi   pop2021     area
rank
1                Macau  21946.4667  56841.3487   658.394       30
2               Monaco  19755.5000  51166.7450    39.511        2
3            Singapore   8305.1915  21510.4461  5896.686      710
4            Hong Kong   6841.3134  17719.0017  7552.810     1104
5            Gibraltar   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
228            Namibia      3.1338      8.1166  2587.344   825615
229     Western Sahara      2.3003      5.9577   611.875   266000
230           Mongolia      2.1286      5.5129  3329.289  1564110
231   Falkland Islands      0.2902      0.7517     3.533    12173
232          Greenland      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

### 1-VAZIFA. Yuqoridagi DF ustunlari nomini quyidagi qiymatlarga o'zgartiring va DF yuqorisidan 3 ta davlatni chiqaring
`['davlat','zichlik_km','zichlik_mi','aholi','maydoni']`

In [3]:
# JAVOBNI SHUYERGA YOZING
df.rename(columns={"country": "davlat","density":"zichlik_km", "densityMi": "zichlik_mi" , "pop2021":"aholi", "area": "maydoni"}, inplace=True)
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

In [4]:
#@title To'g'ri javob
df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

## Yuqoridagi jadval dunyo davlatlarining aholi zichligi bo'yicha reytingini ko'rsatadi.
DF indeksi sifatida davlatning zichlik reytingi olingan (aholi eng zich yashaydigan davlatlar yuqorida).

**Ustunlar:**

`davlat` - Davlat nomi

`zichlik_km` - har 1 kv.km. ga to'g'ri keluvchi aholi soni

`zichlik_mi` - har 1 kv.milyaga to'g'ri keluvchi aholi soni (milya - AQSh masofa o'lchov birligi)

`aholi` - 2021-yilga ko'rsa aholi soni (ming)

`maydoni` - davlat maydoni (kv.km)

### 2-VAZIFA. DF oxiridan 10 ta qator chiqaring.

In [5]:
# JAVOBNI SHUYERGA YOZING
df.tail(10)

                davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
223             Guyana      3.6765      9.5220    790.326   214969
224      French Guiana      3.6685      9.5015    306.448    83534
225           Suriname      3.6125      9.3564    591.800   163820
226          Australia      3.3526      8.6832  25788.215  7692024
227            Iceland      3.3335      8.6338    343.353   103000
228            Namibia      3.1338      8.1166   2587.344   825615
229     Western Sahara      2.3003      5.9577    611.875   266000
230           Mongolia      2.1286      5.5129   3329.289  1564110
231   Falkland Islands      0.2902      0.7517      3.533    12173
232          Greenland      0.0263      0.0680     56.877  2166086

### 3-VAZIFA. DF dan 10, 20, 100, 200-indekslarda turgan davlatlarni alohida DF ko'rinishida chiqaring.

In [6]:
# JAVOBNI SHUYERGA YOZING
df2 = df.iloc[['10','20','100','200']]
df2

          davlat  zichlik_km  zichlik_mi       aholi  maydoni
rank
11    Bangladesh   1126.9465   2918.7915  166303.498   147570
21    San Marino    557.6557   1444.3284      34.017       61
101        Benin    110.5560    286.3401   12451.040   112622
201     Paraguay     17.7495     45.9712    7219.638   406752

In [7]:
df.davlat

rank
1                 Macau
2                Monaco
3             Singapore
4             Hong Kong
5             Gibraltar
             ...
228             Namibia
229      Western Sahara
230            Mongolia
231    Falkland Islands
232           Greenland
Name: davlat, Length: 232, dtype: str

### 4-VAZIFA. Davlatlar orasida `Uzbekistan`, `Hong-Kong`, `Antartica` borligini tekshiring

In [8]:
# JAVOBNI SHUYERGA YOZING
davlat = ["Uzbekistan", "Hong Kong", "Antarctica"]
df[df['davlat'].isin(davlat)]

          davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
4      Hong Kong   6841.3134  17719.0017   7552.810     1104
133   Uzbekistan     75.8511    196.4542  33935.763   447400

### 5-VAZIFA.
#### 5.1 DFning `davlat` nomli ustunini uning indeksi qilib belgilang.
#### 5.2 `davlat` ustunini tashlab yuboring.
#### 5.3 DFni davlat nomi bo'yicha tartiblang

In [9]:
# JAVOBNI SHUYERGA YOZING
df.set_index('davlat', inplace=True)
df.sort_index(inplace=True)
df

                   zichlik_km  zichlik_mi      aholi  maydoni
davlat
Afghanistan           61.0757    158.1862  39835.428   652230
Albania               99.9351    258.8318   2872.933    28748
Algeria               18.7328     48.5179  44616.624  2381741
American Samoa       276.8844    717.1307     55.100      199
Andorra              165.2885    428.0971     77.355      468
...                       ...         ...        ...      ...
Wallis and Futuna     78.1268    202.3483     11.094      142
Western Sahara         2.3003      5.9577    611.875   266000
Yemen                 57.7509    149.5749  30490.640   527968
Zambia                25.1400     65.1125  18920.651   752612
Zimbabwe              38.6229    100.0333  15092.171   390757

[232 rows x 4 columns]

In [10]:
#@title Kutilayotgan natija

### 6-VAZIFA. DF dan `Uzbekistan`, `Malaysia`, `South Korea`, `France` davlatlari `aholi` va `maydoni` ustunlari bilan alohida DF ko'rinishida ajratib oling.

In [11]:
# JAVOBNI SHUYERGA YOZING
davlatlar = ["Uzbekistan", "Malaysia", "South Korea", "France"]
df2 = df.loc[davlatlar, ["aholi", "maydoni"]]
df2

                 aholi  maydoni
davlat
Uzbekistan   33935.763   447400
Malaysia     32776.194   330803
South Korea  51305.186   100210
France       65426.179   551695

In [12]:
#@title O'xshash natija (boshqa davlatlar uchun)
davlatlar = ["Uzbekistan", "Malaysia", "South Korea", "France"]
df3 = df.loc[~df.index.isin(davlatlar), ["aholi", "maydoni"]]
df3

                       aholi  maydoni
davlat
Afghanistan        39835.428   652230
Albania             2872.933    28748
Algeria            44616.624  2381741
American Samoa        55.100      199
Andorra               77.355      468
...                      ...      ...
Wallis and Futuna     11.094      142
Western Sahara       611.875   266000
Yemen              30490.640   527968
Zambia             18920.651   752612
Zimbabwe           15092.171   390757

[228 rows x 2 columns]

### 7-VAZIFA. Asl DFning `aholi` ustuni qiymatlarini 1000 ga ko'paytiring.

In [13]:
# JAVOBNI SHUYERGA YOZING
df.aholi *1000

davlat
Afghanistan          39835428.0
Albania               2872933.0
Algeria              44616624.0
American Samoa          55100.0
Andorra                 77355.0
                        ...
Wallis and Futuna       11094.0
Western Sahara         611875.0
Yemen                30490640.0
Zambia               18920651.0
Zimbabwe             15092171.0
Name: aholi, Length: 232, dtype: float64

In [14]:
#@title Kutilgan natija

DF ni `aholi` ustuni bo'yicha kamayish tartibida tahlang va aholisi eng kam 10 ta davlatni chiqaring.

In [15]:
# JAVOBNI SHUYERGA YOZING
df.sort_values('aholi', ascending=False).tail(10)

                           zichlik_km  zichlik_mi   aholi  maydoni
davlat
Tuvalu                       458.8846   1188.5112  11.931       26
Wallis and Futuna             78.1268    202.3483  11.094      142
Nauru                        517.9048   1341.3733  10.876       21
Saint Barthelemy             471.7619   1221.8633   9.907       21
Saint Pierre and Miquelon     23.8264     61.7105   5.766      242
Montserrat                    48.7941    126.3768   4.977      102
Falkland Islands               0.2902      0.7517   3.533    12173
Niue                           6.2269     16.1277   1.619      260
Tokelau                      114.4167    296.3392   1.373       12
Vatican City                 800.0000   2072.0000   0.800        1

### 8-VAZIFA. DFni `maydoni` bo'yicha reytinglang (rank) va reytinglarni yangi `rank` ustuniga yozing.

In [16]:
# JAVOBNI SHUYERGA YOZING
df['rank'] = df['maydoni'].rank()
df

                   zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835.428   652230  192.0
Albania               99.9351    258.8318   2872.933    28748   89.0
Algeria               18.7328     48.5179  44616.624  2381741  223.0
American Samoa       276.8844    717.1307     55.100      199   20.0
Andorra              165.2885    428.0971     77.355      468   38.0
...                       ...         ...        ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11.094      142   15.0
Western Sahara         2.3003      5.9577    611.875   266000  155.0
Yemen                 57.7509    149.5749  30490.640   527968  183.0
Zambia                25.1400     65.1125  18920.651   752612  194.0
Zimbabwe              38.6229    100.0333  15092.171   390757  172.0

[232 rows x 5 columns]

In [17]:
#@title Kutilgan natija
df

                   zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835.428   652230  192.0
Albania               99.9351    258.8318   2872.933    28748   89.0
Algeria               18.7328     48.5179  44616.624  2381741  223.0
American Samoa       276.8844    717.1307     55.100      199   20.0
Andorra              165.2885    428.0971     77.355      468   38.0
...                       ...         ...        ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11.094      142   15.0
Western Sahara         2.3003      5.9577    611.875   266000  155.0
Yemen                 57.7509    149.5749  30490.640   527968  183.0
Zambia                25.1400     65.1125  18920.651   752612  194.0
Zimbabwe              38.6229    100.0333  15092.171   390757  172.0

[232 rows x 5 columns]

#### `Uzbekistan`, `United Kingdom`, `Indonesia` davlatlari alohida df ko'rinishida chiqaring

In [18]:
# JAVOBNI SHUYERGA YOZING
dav = ['Uzbekistan','United Kingdom','Indonesia']
df4 = df.loc[dav]
df4

                zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Uzbekistan         75.8511    196.4542   33935.763   447400  176.0
United Kingdom    280.8033    727.2805   68207.116   242900  153.0
Indonesia         145.1046    375.8210  276361.783  1904569  218.0

In [19]:
#@title O'xshash natija (boshqa davlatlar uchun)

### 9-VAZIFA. DFni `davlat` nomi bo'yicha tartiblang.

In [20]:
# JAVOBNI SHUYERGA YOZING
df.sort_index(inplace=True)
df

                   zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835.428   652230  192.0
Albania               99.9351    258.8318   2872.933    28748   89.0
Algeria               18.7328     48.5179  44616.624  2381741  223.0
American Samoa       276.8844    717.1307     55.100      199   20.0
Andorra              165.2885    428.0971     77.355      468   38.0
...                       ...         ...        ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11.094      142   15.0
Western Sahara         2.3003      5.9577    611.875   266000  155.0
Yemen                 57.7509    149.5749  30490.640   527968  183.0
Zambia                25.1400     65.1125  18920.651   752612  194.0
Zimbabwe              38.6229    100.0333  15092.171   390757  172.0

[232 rows x 5 columns]

In [21]:
#@title Kutilgan natija

#### DFdan 10,50,100,200-o'rinda turgan davlatlarni alohida DF ko'rinishida chiqaring

In [22]:
# JAVOBNI SHUYERGA YOZING
df5 = df.iloc[[10,50,100,200]]
df5

                zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Aruba             595.5778   1542.5464    107.204      180   18.0
Czech Republic    135.9862    352.2044  10724.555    78865  115.0
Jamaica           270.5362    700.6887   2973.463    10991   68.0
Syria              98.6916    255.6111  18275.702   185180  144.0

In [23]:
#@title O'xshash natija (boshqa qatorlar uchun)

### 10-VAZIFA. Quyidagi davlatlarning `aholi` sonini oddiy son ko'rinishida chiqaring:
- `Malaysia`
- `Nigeria`
- `Nepal`
- `Italy`

In [24]:
# JAVOBNI SHUYERGA YOZING
davlats = ["Malaysia", "Nigeria", "Nepal", "Italy"]
davlats = df.loc[davlats]
davlats.aholi.tolist()

[32776.194, 211400.708, 29674.92, 60367.477]

In [25]:
#@title o'xshash natija (`Uzbekistan` uchun)

In [26]:
df

                   zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835.428   652230  192.0
Albania               99.9351    258.8318   2872.933    28748   89.0
Algeria               18.7328     48.5179  44616.624  2381741  223.0
American Samoa       276.8844    717.1307     55.100      199   20.0
Andorra              165.2885    428.0971     77.355      468   38.0
...                       ...         ...        ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11.094      142   15.0
Western Sahara         2.3003      5.9577    611.875   266000  155.0
Yemen                 57.7509    149.5749  30490.640   527968  183.0
Zambia                25.1400     65.1125  18920.651   752612  194.0
Zimbabwe              38.6229    100.0333  15092.171   390757  172.0

[232 rows x 5 columns]

In [27]:
df.sort_values('zichlik_mi')

                  zichlik_km  zichlik_mi     aholi  maydoni   rank
davlat
Greenland             0.0263      0.0680    56.877  2166086  221.0
Falkland Islands      0.2902      0.7517     3.533    12173   70.0
Mongolia              2.1286      5.5129  3329.289  1564110  214.0
Western Sahara        2.3003      5.9577   611.875   266000  155.0
Namibia               3.1338      8.1166  2587.344   825615  198.0
...                      ...         ...       ...      ...    ...
Gibraltar          5616.3333  14546.3033    33.698        6    3.0
Hong Kong          6841.3134  17719.0017  7552.810     1104   50.0
Singapore          8305.1915  21510.4461  5896.686      710   43.0
Monaco            19755.5000  51166.7450    39.511        2    2.0
Macau             21946.4667  56841.3487   658.394       30    8.0

[232 rows x 5 columns]

In [28]:
df.sort_values('zichlik_km')

                  zichlik_km  zichlik_mi     aholi  maydoni   rank
davlat
Greenland             0.0263      0.0680    56.877  2166086  221.0
Falkland Islands      0.2902      0.7517     3.533    12173   70.0
Mongolia              2.1286      5.5129  3329.289  1564110  214.0
Western Sahara        2.3003      5.9577   611.875   266000  155.0
Namibia               3.1338      8.1166  2587.344   825615  198.0
...                      ...         ...       ...      ...    ...
Gibraltar          5616.3333  14546.3033    33.698        6    3.0
Hong Kong          6841.3134  17719.0017  7552.810     1104   50.0
Singapore          8305.1915  21510.4461  5896.686      710   43.0
Monaco            19755.5000  51166.7450    39.511        2    2.0
Macau             21946.4667  56841.3487   658.394       30    8.0

[232 rows x 5 columns]

In [29]:
df.sort_values('aholi')

                  zichlik_km  zichlik_mi        aholi  maydoni   rank
davlat
Vatican City        800.0000   2072.0000        0.800        1    1.0
Tokelau             114.4167    296.3392        1.373       12    4.0
Niue                  6.2269     16.1277        1.619      260   23.0
Falkland Islands      0.2902      0.7517        3.533    12173   70.0
Montserrat           48.7941    126.3768        4.977      102   14.0
...                      ...         ...          ...      ...    ...
Pakistan            255.3542    661.3674   225199.937   881912  199.0
Indonesia           145.1046    375.8210   276361.783  1904569  218.0
United States        35.5200     91.9968   332915.073  9372610  229.0
India               423.8391   1097.7432  1393409.038  3287590  226.0
China               148.7815    385.3441  1444216.107  9706961  230.0

[232 rows x 5 columns]

In [38]:
df[df.index.isin(["Antarctica"])]

Empty DataFrame
Columns: [zichlik_km, zichlik_mi, aholi, maydoni, rank]
Index: []

In [46]:
df.index

RangeIndex(start=1, stop=233, step=1, name='rank')

In [47]:
df.country.nunique()

232

In [48]:
df

               country     density   densityMi   pop2021     area
rank
1                Macau  21946.4667  56841.3487   658.394       30
2               Monaco  19755.5000  51166.7450    39.511        2
3            Singapore   8305.1915  21510.4461  5896.686      710
4            Hong Kong   6841.3134  17719.0017  7552.810     1104
5            Gibraltar   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
228            Namibia      3.1338      8.1166  2587.344   825615
229     Western Sahara      2.3003      5.9577   611.875   266000
230           Mongolia      2.1286      5.5129  3329.289  1564110
231   Falkland Islands      0.2902      0.7517     3.533    12173
232          Greenland      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]