![Imgur](https://i.imgur.com/h4PPC71.png)

#Data Sayns va Sunʼiy Intellekt Praktikum

#9.32. Pandas kutubxonasi boʻyicha amaliy vazifa.

Yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirilgan`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va uni chop eting.

In [252]:
import pandas as pd

**2.** Versiya va konfiguratsiyani tekshiring.

In [253]:
pd.__version__

'2.2.2'

**3.** Pandas kutubxonasida mavjud boʻlgan barcha versiya maʼlumotlarini chop eting.

In [254]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.6.113+
Version               : #1 SMP Mon Feb  2 12:27:57 UTC 2026
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.4.2
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 6.0.2
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.11
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.0
gcsfs                 : 2025.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.30.0
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.3
sqlalchemy            : 2.0.48
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.12.0
xlrd                  : 2.0.2
zstandard             : 0.25.0
tzdata                : 2025.3
qtpy                  : None
pyqt5                 : None

## `📌DataFrame: Asoslar`

DataFramesʼda maʼlumotlarni tanlash (selecting), saralash (sorting), qoʻshish (adding) va yigʻish (aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang.
``` python
import numpy as np
```

Quyidagi Python lugʻati (dictionary) `data` va Python roʻyxati (list) `labels` ni koʻrib chiqing.


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [255]:
import numpy as np

In [256]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [257]:
df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [258]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [259]:
df[['animal','visits']]

  animal  visits
a    cat       1
b    cat       3
c  snake       2
d    dog       3
e    dog       2
f    cat       3
g  snake       1
h    cat       1
i    dog       2
j    dog       1

In [260]:
df.iloc[:,3]

a    yes
b    yes
c     no
d    yes
e     no
f     no
g     no
h    yes
i     no
j     no
Name: priority, dtype: object

In [261]:
df.sort_values('age')

  animal  age  visits priority
c  snake  0.5       2       no
f    cat  2.0       3       no
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no
g  snake  4.5       1       no
e    dog  5.0       2       no
i    dog  7.0       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [262]:
df[df.age >1]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
i    dog  7.0       2       no
j    dog  3.0       1       no

In [263]:
df[df.age.isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [264]:
df[~df.age.isnull()] #  ~ belgi inkor qilib yuborar ekan

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
i    dog  7.0       2       no
j    dog  3.0       1       no

In [265]:
df.age.mean()

np.float64(3.4375)

In [266]:
df.visits.sum()
df['visits'].sum() # desayam bo'ladi

np.int64(19)

**4.** Ushbu `lugʻat` (dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [267]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Ushbu DataFrame va uning maʼlumotlari haqidagi asosiy maʼlumotlarning qisqacha mazmunini koʻrsating.

`💡Ishora:` DataFrameʼda chaqirilishi mumkin boʻlgan yagona usul mavjud.

In [268]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [269]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** DataFrame `df`ʼdan faqat `animal` va `age` ustunlarini tanlang.

In [270]:
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi maʼlumotlarni tanlang.

In [271]:
df.iloc[[3,4,8], [0, 1]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Faqat `visits` soni 3 tadan koʻp boʻlgan qatorlarni tanlang.

In [272]:
df[df.visits >=3] # 3 tadan katta qilsam hech narsa chiqmadi, shunga = qo'shib qo'ydim

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

10. Yosh yoʻqolgan qatorlarni tanlang, yaʼni `NaN`.

In [273]:
df[df.age.isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik boʻlgan umumiy qatorlarni tanlang.

In [274]:
df[(df.animal == 'cat') & (df.age <3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [275]:
df[(df.age >=2) & (df.age<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** `f` qatoridagi yoshni `1,5` ga oʻzgartiring.

In [276]:
df.loc["f","age"] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** `df` yordamida `visits` qatorining yigʻindisini hisoblang.

In [277]:
df.visits.sum()

np.int64(19)

**15.** Har bir `animal` uchun oʻrtacha yoshni `df` da hisoblang.

In [278]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [279]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**17.** `animal` ustunida, `snake` soʻzini `python` soʻziga oʻzgartiring.

In [280]:
df['animal'] = df['animal'].replace('snake','python')
df

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

## `📌DataFrame: Murakkab`

### Darajasi murakkabroq vazifa: toʻgʻri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak boʻlishi mumkin

Oldingi boʻlim DataFrameʼning asosiy, ammo muhim operatsiyalari boʻyicha vazifalari jamlagan edi. Quyida maʼlumotlarni kesishingiz kerak boʻlgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni oʻz ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni oʻz ichiga olgan ustun paydo boʻlishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [281]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df

    A
0   1
1   2
2   2
3   3
4   4
5   5
6   5
7   5
8   6
9   7
10  7

In [282]:
df2 = pd.DataFrame( {"A": df['A'].unique()})
df2

   A
0  1
1  2
2  3
3  4
4  5
5  6
6  7

**19.** Raqamli qiymatlardan iborat DataFrame berildi.

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 oʻlchovi
```

Qatordagi har bir elementdan satrning oʻrtacha qiymatini qanday ayirish mumkin?

In [283]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df

          0         1         2
0  0.249731  0.771728  0.016889
1  0.945589  0.491428  0.985621
2  0.903313  0.806283  0.080946
3  0.045562  0.793130  0.383737
4  0.292335  0.055222  0.086358

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yigʻindisi eng kichik ekanini hisoblang. U ustunning yorligʻini qaytaring.

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrameʼning har bir qatori uchun uchinchi `NaN` qiymatini oʻz ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [284]:
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

res = df.isnull().cumsum(axis=1) ==3
res.idxmax(axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [285]:
# Javobni bu yerga yozing.
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
res=df.groupby('grps')['vals'].nlargest(3).groupby(level=0).sum()
res

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega `A` va `B`. `A` dagi qiymatlar 1 dan 100 gacha (shu jumladan).

`A` dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yigʻindisini hisoblang.

Javob quyidagicha boʻlishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [286]:
import pandas as pd
import numpy as np

# 1. Siz bergan DataFrame
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# 2. Guruhlarni belgilash (0, 10, 20... 100)
bins = np.arange(0, 101, 10)

# 3. Hisoblash
# pd.cut A ni guruhga bo'ladi, groupby esa B ni o'sha guruhlar bo'yicha qo'shadi
result = df.groupby(pd.cut(df['A'], bins=bins))['B'].sum()

print(result)





#shu masalani hech tushunmadimda, AI yozib berdi, lekin tushunolmadim, nega bunaqa bo'lyapti bilmayapman

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

/tmp/ipykernel_9756/2429466033.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(pd.cut(df['A'], bins=bins))['B'].sum()

**24.** 'X' butun son ustuni boʻlgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha boʻlishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [287]:
#javobni bu yerga yozing!
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
# 1. Nol bo'lmagan joylarni 1, nol bo'lgan joylarni 0 qilib belgilaymiz
x = (df['X'] != 0).cumsum()

# 2. Faqat nollarning o'rnini (indeksini) topib olamiz
y = x.where(df['X'] == 0)

# 3. Guruhlash orqali har bir noldan keyingi masofani chiqaramiz
df['Y'] = x - y.ffill().fillna(0).astype(int)
df

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

##`📌Maʼlumotlarni tozalash`

Bu har doim sodir boʻladi: kimdir sizga notoʻgʻri tuzilgan satrlar, roʻyxatlar va yetishmayotgan maʼlumotlarni oʻz ichiga olgan maʼlumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan soʻng u quyidagi koʻrinishga ega boʻlishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```

In [288]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

**26.** **FlightNumber** ustunidagi baʼzi qiymatlar yoʻq. Ular `NaN` koʻrinishida yozilgan. Bu raqamlar har bir qatorda 10 ga koʻpayishi kerak, shuning uchun 10055 va 10075 ni qoʻyish kerak. Ushbu yetishmayotgan raqamlarni toʻldirish uchun `df` ni oʻzgartiring va ustunni butun son ustuniga aylantiring.

In [289]:
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**27.** **From\_To** ustunini ikkita alohida ustun koʻrinishida yozing.                                          

Toʻgʻri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [290]:
temp  = df["From_To"].str.split('_', expand=True)
temp.columns = ['From', 'To']
temp

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.
Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" boʻlishi kerak.)

In [291]:
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()
temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va boshqa belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ''(British Airways. )'' `British Airways` koʻrinishida yozilishi kerak.

In [292]:
df['Airline']= df['Airline'].str.replace('[^a-zA-Z]', '', regex=True).str.strip()
df

            From_To  FlightNumber  RecentDelays         Airline
0      LoNDon_paris         10045      [23, 47]             KLM
1      MAdrid_miLAN         10055            []       AirFrance
2  londON_StockhOlm         10065  [24, 43, 87]  BritishAirways
3    Budapest_PaRis         10075          [13]       AirFrance
4   Brussels_londOn         10085      [67, 32]        SwissAir

**30.** `df` dan **From_To** ustunini oʻchiring va Temporary DataFrame `temp` ustunini qoʻshing.

In [293]:
df = df.drop('From_To',axis=1)
df

   FlightNumber  RecentDelays         Airline
0         10045      [23, 47]             KLM
1         10055            []       AirFrance
2         10065  [24, 43, 87]  BritishAirways
3         10075          [13]       AirFrance
4         10085      [67, 32]        SwissAir

In [294]:
df = df.join(temp)
df

   FlightNumber  RecentDelays         Airline      From         To
0         10045      [23, 47]             KLM    London      Paris
1         10055            []       AirFrance    Madrid      Milan
2         10065  [24, 43, 87]  BritishAirways    London  Stockholm
3         10075          [13]       AirFrance  Budapest      Paris
4         10085      [67, 32]        SwissAir  Brussels     London

**31**. `RecentDelays` ustunida qiymatlar DataFrameʼga roʻyxat sifatida kiritilgan. Vazifangiz birinchi, har bir ikkinchi qiymatni oʻz ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat boʻlmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi koʻrinishda boʻlishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [295]:
delays = df['RecentDelays'].apply(pd.Series)
delays.columns = [f'delay_{i+1}' for i in range(len(delays.columns))]
df = df.drop('RecentDelays', axis=1).join(delays)
df

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045,KLM,London,Paris,23.0,47.0,NaN
1,10055,AirFrance,Madrid,Milan,NaN,NaN,NaN
2,10065,BritishAirways,London,Stockholm,24.0,43.0,87.0
3,10075,AirFrance,Budapest,Paris,13.0,NaN,NaN
4,10085,SwissAir,Brussels,London,67.0,32.0,NaN

##`📌Minesweeper`


### Minesweeper tarmogʻida xavfsiz kvadratlar uchun raqamlar yaratamiz.

💡 Agar siz Windowsʼning avvalgi versiyalaridan foydalangan boʻlsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz oʻyin bilan tanish boʻlmasangiz, kvadratchalar toʻplamini tasavvur qiling: bu kvadratlarning baʼzilari mineʼni yashiradi. Agar siz mineʼni bossangiz, darhol yoʻqotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qoʻshni boʻlgan kvadratchalarda qancha mine borligini koʻrsatadigan raqamni koʻrasiz. Oʻyinning maqsadi toʻrdagi mine boʻlmagan barcha kvadratlarni ochishdir.

Ushbu boʻlimda Minesweeper oʻyini uchun kerakli maʼlumotlarni oʻz ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qoʻshni kvadratlarda topilgan mineʼlar sonini aniqlaymiz.

**32**. Tasavvur qiling, biz Minesweeper oʻyinini 5 dan 4 gacha boʻlgan panjarada oʻynayapmiz, yaʼni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani oʻz ichiga olgan `'x'` va `'y'`. Yaʼni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [296]:
import pandas as pd
import numpy as np

X = 5
Y = 4

# 1. Barcha x va y koordinatalari kombinatsiyasini yaratamiz
# np.arange(X) -> [0, 1, 2, 3, 4]
# np.arange(Y) -> [0, 1, 2, 3]
x, y = np.meshgrid(np.arange(X), np.arange(Y))

# 2. Ushbu koordinatalarni bitta DataFrame'ga yig'amiz
df = pd.DataFrame({
    'x': x.flatten(),
    'y': y.flatten()
})

df

    x  y
0   0  0
1   1  0
2   2  0
3   3  0
4   4  0
5   0  1
6   1  1
7   2  1
8   3  1
9   4  1
10  0  2
11  1  2
12  2  2
13  3  2
14  4  2
15  0  3
16  1  3
17  2  3
18  3  3
19  4  3

**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir boʻlish ehtimoli 0,4 boʻlishi kerak.

In [297]:

df['mine'] = np.random.binomial(1, 0.4, len(df))

df

    x  y  mine
0   0  0     0
1   1  0     1
2   2  0     0
3   3  0     0
4   4  0     1
5   0  1     0
6   1  1     0
7   2  1     1
8   3  1     0
9   4  1     0
10  0  2     0
11  1  2     0
12  2  2     1
13  3  2     0
14  4  2     0
15  0  3     1
16  1  3     0
17  2  3     1
18  3  3     0
19  4  3     1

 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qoʻshni kvadratlarda topilgan mineʼlar soni boʻlishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv boʻlgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [298]:
def count_adjacent_mines(row, df):
    x, y = row['x'], row['y']
    neighbors = df[
        (df['x'].between(x-1, x+1)) &
        (df['y'].between(y-1, y+1)) &
        ~((df['x'] == x) & (df['y'] == y))
    ]

    return neighbors['mine'].sum()
df['adjacent'] = df.apply(count_adjacent_mines, axis=1, df=df)

df

    x  y  mine  adjacent
0   0  0     0         1
1   1  0     1         1
2   2  0     0         2
3   3  0     0         2
4   4  0     1         0
5   0  1     0         1
6   1  1     0         3
7   2  1     1         2
8   3  1     0         3
9   4  1     0         1
10  0  2     0         1
11  1  2     0         4
12  2  2     1         2
13  3  2     0         4
14  4  2     0         1
15  0  3     1         0
16  1  3     0         3
17  2  3     1         1
18  3  3     0         3
19  4  3     1         0

**35**. Mineʼni oʻz ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga oʻzgartiring.

In [299]:
df.loc[df['mine'] == 1, 'adjacent'] = np.nan
df

    x  y  mine  adjacent
0   0  0     0       1.0
1   1  0     1       NaN
2   2  0     0       2.0
3   3  0     0       2.0
4   4  0     1       NaN
5   0  1     0       1.0
6   1  1     0       3.0
7   2  1     1       NaN
8   3  1     0       3.0
9   4  1     0       1.0
10  0  2     0       1.0
11  1  2     0       4.0
12  2  2     1       NaN
13  3  2     0       4.0
14  4  2     0       1.0
15  0  3     1       NaN
16  1  3     0       3.0
17  2  3     1       NaN
18  3  3     0       3.0
19  4  3     1       NaN

**36**. DataFrame-ni `adjacent` mineʼlar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [300]:
grid = df.pivot(index='y', columns='x', values='adjacent')
grid

x    0    1    2    3    4
y
0  1.0  NaN  2.0  2.0  NaN
1  1.0  3.0  NaN  3.0  1.0
2  1.0  4.0  NaN  4.0  1.0
3  NaN  3.0  NaN  3.0  NaN

##📌BONUS vazifa

Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.

`df` ni ko'rsat

In [301]:
df

    x  y  mine  adjacent
0   0  0     0       1.0
1   1  0     1       NaN
2   2  0     0       2.0
3   3  0     0       2.0
4   4  0     1       NaN
5   0  1     0       1.0
6   1  1     0       3.0
7   2  1     1       NaN
8   3  1     0       3.0
9   4  1     0       1.0
10  0  2     0       1.0
11  1  2     0       4.0
12  2  2     1       NaN
13  3  2     0       4.0
14  4  2     0       1.0
15  0  3     1       NaN
16  1  3     0       3.0
17  2  3     1       NaN
18  3  3     0       3.0
19  4  3     1       NaN