In [2]:
import pandas as pd
import numpy as np

data = pd.Series(np.random.randn(9), index=['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd']) # odatiy
data

a   -0.770105
a   -1.027704
a   -0.417505
b   -1.212518
b   -0.364787
c   -0.604352
c    1.044670
d   -1.313117
d   -0.666346
dtype: float64

In [3]:
data1 = pd.Series(np.random.randn(9),index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],[1, 2, 3, 1, 3, 1, 2, 2, 3]]) # ierarxik
data1

a  1    0.792043
   2   -0.320463
   3   -0.993896
b  1   -0.722510
   3    0.828350
c  1   -0.922239
   2    0.892832
d  2    0.415596
   3    3.364291
dtype: float64

### Ma'lumotlarni ajratib olish

In [4]:
data1

a  1    0.792043
   2   -0.320463
   3   -0.993896
b  1   -0.722510
   3    0.828350
c  1   -0.922239
   2    0.892832
d  2    0.415596
   3    3.364291
dtype: float64

In [5]:
data1['a'] # subset ajratish

1    0.792043
2   -0.320463
3   -0.993896
dtype: float64

In [6]:
data1['c': 'd'] # slice ya'ni c dan d gacha

c  1   -0.922239
   2    0.892832
d  2    0.415596
   3    3.364291
dtype: float64

In [7]:
data1.loc[:, 2]  # 2-indeksli qiymatlar

a   -0.320463
c    0.892832
d    0.415596
dtype: float64

In [8]:
data1.loc[['a', 'c']] # a va c qatorlarini olish

a  1    0.792043
   2   -0.320463
   3   -0.993896
c  1   -0.922239
   2    0.892832
dtype: float64

## unstack

In [9]:
data1

a  1    0.792043
   2   -0.320463
   3   -0.993896
b  1   -0.722510
   3    0.828350
c  1   -0.922239
   2    0.892832
d  2    0.415596
   3    3.364291
dtype: float64

In [10]:
data1.unstack() # sochilgan Series ni DataFrame ga aylantirish

          1         2         3
a  0.792043 -0.320463 -0.993896
b -0.722510       NaN  0.828350
c -0.922239  0.892832       NaN
d       NaN  0.415596  3.364291

### stack

In [11]:
data1.unstack().stack() # DataFrame ni yig'ilgan Series ga aylantirish

a  1    0.792043
   2   -0.320463
   3   -0.993896
b  1   -0.722510
   2         NaN
   3    0.828350
c  1   -0.922239
   2    0.892832
   3         NaN
d  1         NaN
   2    0.415596
   3    3.364291
dtype: float64

### Dunyo shaharlarining havo va suv sifati ma'lumotlari ustida amallar bajarish

In [12]:
!wget https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/world_cities_air_water_quality.csv

--2026-05-05 11:51:33--  https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/world_cities_air_water_quality.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 235604 (230K) [text/plain]
Saving to: ‘world_cities_air_water_quality.csv.1’

world_cities_air_wa 100%[===================>] 230.08K  93.3KB/s    in 2.5s

2026-05-05 11:52:18 (93.3 KB/s) - ‘world_cities_air_water_quality.csv.1’ saved [235604/235604]

In [13]:
df = pd.read_csv('world_cities_air_water_quality.csv')
df

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3963 entries, 0 to 3962
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               3963 non-null   str
 1    "Region"          3963 non-null   str
 2    "Country"         3963 non-null   str
 3    "AirQuality"      3963 non-null   float64
 4    "WaterPollution"  3963 non-null   float64
dtypes: float64(2), str(3)
memory usage: 154.9 KB

In [15]:
columns = ['City', 'Region', 'Country', 'AirQuality', 'WaterPollution']
df.columns = columns
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [16]:
df['Region'] = df['Region'].map(lambda x: x.replace('"', ''))

In [17]:
df['Country'] = df['Country'].map(lambda x: x.replace('"', ''))

In [18]:
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [19]:
df.to_csv('updated_dataset.csv', index=False)

In [20]:
df[df['Country'] == 'Germany']

Empty DataFrame
Columns: [City, Region, Country, AirQuality, WaterPollution]
Index: []

In [21]:
df['Country'] = df['Country'].map(lambda x: x.strip())
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [22]:
df[df['Country'] == 'Germany']

,City,Region,Country,AirQuality,WaterPollution
3,Berlin,,Germany,62.364130,28.612717
28,Cologne,North Rhine-Westphalia,Germany,60.714286,27.777778
40,Bonn,North Rhine-Westphalia,Germany,82.812500,22.500000
52,Heilbronn,Baden-Wurttemberg,Germany,80.000000,0.000000
76,Aachen,North Rhine-Westphalia,Germany,70.454545,17.857143
...,...,...,...,...,...
2693,Bad Waldsee,Baden-Wurttemberg,Germany,100.000000,50.000000
2714,Weilheim in Oberbayern,Bavaria,Germany,100.000000,50.000000
2727,Buckow,Brandenburg,Germany,87.500000,50.000000
3942,Erfurt,Thuringia,Germany,85.000000,50.000000
3943,Garmisch-Partenkirchen,Bavaria,Germany,100.000000,50.000000

In [23]:
df[df['Country'] == 'Uzbekistan']

        City Region     Country  AirQuality  WaterPollution
21  Tashkent         Uzbekistan   56.451613       49.166667

### ```pivot table``` orqali iyerarxik indexlash

In [24]:
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [25]:
df1 = pd.pivot_table(df, index=['Country', 'City'])
df1

TypeError: dtype 'str' does not support operation 'mean'

In [26]:
df1 = pd.pivot_table(df, 
                     index=['Country', 'City'], 
                     values=['AirQuality', 'WaterPollution'])
df1

                      AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000
            Farah     100.000000        0.000000
            Herat      43.750000       31.250000
            Kabul      18.421053       81.060606
            Kandahar    0.000000       75.000000
...                          ...             ...
Zambia      Mansa      75.000000       25.000000
Zimbabwe    Bindura    50.000000       75.000000
            Bulawayo   67.857143       71.428571
            Harare     38.461538       87.500000
            Masvingo   25.000000       62.500000

[3895 rows x 2 columns]

In [27]:
df1.loc[['Uzbekistan', 'Germany']]

                          AirQuality  WaterPollution
Country    City
Uzbekistan Tashkent        56.451613       49.166667
Germany    Aachen          70.454545       17.857143
           Aalen           87.500000       50.000000
           Abensberg      100.000000       50.000000
           Amberg         100.000000       50.000000
...                              ...             ...
           Wilhelmshaven  100.000000       50.000000
           Wolfsburg       96.875000        0.000000
           Worms           60.000000      100.000000
           Wuppertal       90.000000        0.000000
           Zwickau         75.000000       50.000000

[125 rows x 2 columns]

### Ustunlarni iyerarxik ko'rinishga o'tkazish

In [28]:
df2 = df1.copy()
df2

                      AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000
            Farah     100.000000        0.000000
            Herat      43.750000       31.250000
            Kabul      18.421053       81.060606
            Kandahar    0.000000       75.000000
...                          ...             ...
Zambia      Mansa      75.000000       25.000000
Zimbabwe    Bindura    50.000000       75.000000
            Bulawayo   67.857143       71.428571
            Harare     38.461538       87.500000
            Masvingo   25.000000       62.500000

[3895 rows x 2 columns]

In [29]:
df2['AirPollution'] = 100 - df2['AirQuality']
df2['WaterQuality'] = 100 - df2['WaterPollution']
df2

                      AirQuality  WaterPollution  AirPollution  WaterQuality
Country     City
Afghanistan Andkhoy    50.000000       50.000000     50.000000     50.000000
            Farah     100.000000        0.000000      0.000000    100.000000
            Herat      43.750000       31.250000     56.250000     68.750000
            Kabul      18.421053       81.060606     81.578947     18.939394
            Kandahar    0.000000       75.000000    100.000000     25.000000
...                          ...             ...           ...           ...
Zambia      Mansa      75.000000       25.000000     25.000000     75.000000
Zimbabwe    Bindura    50.000000       75.000000     50.000000     25.000000
            Bulawayo   67.857143       71.428571     32.142857     28.571429
            Harare     38.461538       87.500000     61.538462     12.500000
            Masvingo   25.000000       62.500000     75.000000     37.500000

[3895 rows x 4 columns]

In [30]:
df3 = pd.DataFrame(df2.values, 
                  index = df2.index, 
                  columns= [['AIR', 'AIR', 'WATER', 'WATER'], 
                           ['AirQuality', 'AirPollution', 'WaterQuality', 'WaterPollution']])
df3

                             AIR                     WATER
                      AirQuality AirPollution WaterQuality WaterPollution
Country     City
Afghanistan Andkhoy    50.000000    50.000000    50.000000      50.000000
            Farah     100.000000     0.000000     0.000000     100.000000
            Herat      43.750000    31.250000    56.250000      68.750000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Kandahar    0.000000    75.000000   100.000000      25.000000
...                          ...          ...          ...            ...
Zambia      Mansa      75.000000    25.000000    25.000000      75.000000
Zimbabwe    Bindura    50.000000    75.000000    50.000000      25.000000
            Bulawayo   67.857143    71.428571    32.142857      28.571429
            Harare     38.461538    87.500000    61.538462      12.500000
            Masvingo   25.000000    62.500000    75.000000      37.500000

[3895 rows x 4 columns]

In [31]:
df3['AIR']

                      AirQuality  AirPollution
Country     City
Afghanistan Andkhoy    50.000000     50.000000
            Farah     100.000000      0.000000
            Herat      43.750000     31.250000
            Kabul      18.421053     81.060606
            Kandahar    0.000000     75.000000
...                          ...           ...
Zambia      Mansa      75.000000     25.000000
Zimbabwe    Bindura    50.000000     75.000000
            Bulawayo   67.857143     71.428571
            Harare     38.461538     87.500000
            Masvingo   25.000000     62.500000

[3895 rows x 2 columns]

In [32]:
df3.columns.names = ["Object", "Info"]
df3

Object                       AIR                     WATER
Info                  AirQuality AirPollution WaterQuality WaterPollution
Country     City
Afghanistan Andkhoy    50.000000    50.000000    50.000000      50.000000
            Farah     100.000000     0.000000     0.000000     100.000000
            Herat      43.750000    31.250000    56.250000      68.750000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Kandahar    0.000000    75.000000   100.000000      25.000000
...                          ...          ...          ...            ...
Zambia      Mansa      75.000000    25.000000    25.000000      75.000000
Zimbabwe    Bindura    50.000000    75.000000    50.000000      25.000000
            Bulawayo   67.857143    71.428571    32.142857      28.571429
            Harare     38.461538    87.500000    61.538462      12.500000
            Masvingo   25.000000    62.500000    75.000000      37.500000

[3895 rows x 4 columns]

### ```swaplevel```

In [33]:
df3.swaplevel('Country', 'City') # Iyerarxik indexlarni o'rnini almashtirish

Object                       AIR                     WATER
Info                  AirQuality AirPollution WaterQuality WaterPollution
City     Country
Andkhoy  Afghanistan   50.000000    50.000000    50.000000      50.000000
Farah    Afghanistan  100.000000     0.000000     0.000000     100.000000
Herat    Afghanistan   43.750000    31.250000    56.250000      68.750000
Kabul    Afghanistan   18.421053    81.060606    81.578947      18.939394
Kandahar Afghanistan    0.000000    75.000000   100.000000      25.000000
...                          ...          ...          ...            ...
Mansa    Zambia        75.000000    25.000000    25.000000      75.000000
Bindura  Zimbabwe      50.000000    75.000000    50.000000      25.000000
Bulawayo Zimbabwe      67.857143    71.428571    32.142857      28.571429
Harare   Zimbabwe      38.461538    87.500000    61.538462      12.500000
Masvingo Zimbabwe      25.000000    62.500000    75.000000      37.500000

[3895 rows x 4 columns]

```sort_index```

In [34]:
df3.sort_index(level=0, ascending=False)

Object                       AIR                     WATER
Info                  AirQuality AirPollution WaterQuality WaterPollution
Country     City
Zimbabwe    Masvingo   25.000000    62.500000    75.000000      37.500000
            Harare     38.461538    87.500000    61.538462      12.500000
            Bulawayo   67.857143    71.428571    32.142857      28.571429
            Bindura    50.000000    75.000000    50.000000      25.000000
Zambia      Mansa      75.000000    25.000000    25.000000      75.000000
...                          ...          ...          ...            ...
Afghanistan Kandahar    0.000000    75.000000   100.000000      25.000000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Herat      43.750000    31.250000    56.250000      68.750000
            Farah     100.000000     0.000000     0.000000     100.000000
            Andkhoy    50.000000    50.000000    50.000000      50.000000

[3895 rows x 4 columns]