In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv("Practicum_Datasets/IMDb/IMDb_movies.csv")
movies.head()

/tmp/ipykernel_21136/1874337078.py:1: DtypeWarning: Columns (0: year) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv("Practicum_Datasets/IMDb/IMDb_movies.csv")

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN

In [4]:
ratings = pd.read_csv("Practicum_Datasets/IMDb/IMDb_ratings.csv")
ratings.head()

  imdb_title_id  weighted_average_vote  total_votes
0     tt0000009                    5.9          154
1     tt0000574                    6.1          589
2     tt0001892                    5.8          188
3     tt0002101                    5.2          446
4     tt0002130                    7.0         2237

### Merging

In [5]:
pd.merge?

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | lib.NoDefault' = <no_default>,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
    First pandas object to merge.
right : DataFrame or named Series
    Second pandas object to merge.
how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti},
    default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
    * left_anti: use only keys from left frame that are not in right frame, similar
      to SQL left anti join; preserve key order.
    * right_anti: use only keys from right frame that are not in left frame, similar
      to SQL right anti join; preserve key order.
on : Hashable or a sequence of the previous
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : Hashable or a sequence of the previous, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : Hashable or a sequence of the previous, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default False
    This keyword is now ignored; changing its value will have no
    impact on the method.

    .. deprecated:: 3.0.0

        This keyword is ignored and will be removed in pandas 4.0. Since
        pandas 3.0, this method always returns a new object using a lazy
        copy mechanism that defers copies until necessary
        (Copy-on-Write). See the `user guide on Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        for more details.

indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame(
...     {"lkey": ["foo", "bar", "baz", "foo"], "value": [1, 2, 3, 5]}
... )
>>> df2 = pd.DataFrame(
...     {"rkey": ["foo", "bar", "baz", "foo"], "value": [5, 6, 7, 8]}
... )
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on="lkey", right_on="rkey")
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on="lkey", right_on="rkey", suffixes=("_left", "_right"))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on="lkey", right_on="rkey", suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='str')

>>> df1 = pd.DataFrame({"a": ["foo", "bar"], "b": [1, 2]})
>>> df2 = pd.DataFrame({"a": ["foo", "baz"], "c": [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how="inner", on="a")
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how="left", on="a")
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({"left": ["foo", "bar"]})
>>> df2 = pd.DataFrame({"right": [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how="cross")
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      ~/Desktop/Mohirdev_lessons/venv/lib/python3.12/site-packages/pandas/core/reshape/merge.py
Type:      function

In [6]:
movies.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN

In [7]:
ratings.head()

  imdb_title_id  weighted_average_vote  total_votes
0     tt0000009                    5.9          154
1     tt0000574                    6.1          589
2     tt0001892                    5.8          188
3     tt0002101                    5.2          446
4     tt0002130                    7.0         2237

In [8]:
movies_ratings = pd.merge(movies, ratings)
movies_ratings.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget,weighted_average_vote,total_votes
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN,5.9,154
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250,6.1,589
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN,5.8,188
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000,5.2,446
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN,7.0,2237

In [9]:
movies_ratings.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'budget',
       'weighted_average_vote', 'total_votes'],
      dtype='str')

In [10]:
extracted  = movies_ratings[['title', 'year', 'weighted_average_vote' ]]
extracted

                                title  year  weighted_average_vote
0                          Miss Jerry  1894                    5.9
1         The Story of the Kelly Gang  1906                    6.1
2                      Den sorte drøm  1911                    5.8
3                           Cleopatra  1912                    5.2
4                           L'Inferno  1911                    7.0
...                               ...   ...                    ...
85850                         Le lion  2020                    5.3
85851  De Beentjes van Sint-Hildegard  2020                    7.7
85852       Padmavyuhathile Abhimanyu  2019                    7.9
85853               Sokagin Çocuklari  2019                    6.4
85854      La vida sense la Sara Amat  2019                    6.7

[85855 rows x 3 columns]

### Sodda misollar

In [11]:
A = pd.DataFrame({
    'Transport': ['poezd', 'avtomobil', 'kema'],
    'Tezligi': ['70', '180', '45']
})

A

   Transport Tezligi
0      poezd      70
1  avtomobil     180
2       kema      45

In [12]:
B = pd.DataFrame({
    'Transport': ['poezd', 'avtomobil', 'tramvay'],
    'Narxi': ['98000', '10000', '65000']
})

B

   Transport  Narxi
0      poezd  98000
1  avtomobil  10000
2    tramvay  65000

### merge

In [ ]:
merged = pd.merge(A,B) # inner join
merged

   Transport Tezligi  Narxi
0      poezd      70  98000
1  avtomobil     180  10000

In [ ]:
merged_outer = pd.merge(A,B, how='outer') # outer join
merged_outer

   Transport Tezligi  Narxi
0  avtomobil     180  10000
1       kema      45    NaN
2      poezd      70  98000
3    tramvay     NaN  65000

In [ ]:
merged_left = pd.merge(A,B, how='left') # left join
merged_left # faqat left tomondan umumiy bo'lmaganlarini oladi

   Transport Tezligi  Narxi
0      poezd      70  98000
1  avtomobil     180  10000
2       kema      45    NaN

In [17]:
merged_right = pd.merge(A,B, how='right') # right join
merged_right # faqat right tomondan umumiy bo'lmaganlarini oladi

   Transport Tezligi  Narxi
0      poezd      70  98000
1  avtomobil     180  10000
2    tramvay     NaN  65000

In [18]:
A = pd.DataFrame({
    'Transport_turi': ['poezd', 'avtomobil', 'kema'],
    'Tezligi': ['70', '180', '45']
})

A

  Transport_turi Tezligi
0          poezd      70
1      avtomobil     180
2           kema      45

In [19]:
B

   Transport  Narxi
0      poezd  98000
1  avtomobil  10000
2    tramvay  65000

In [20]:
merg = pd.merge(A,B, left_on='Transport_turi', right_on='Transport')
merg

  Transport_turi Tezligi  Transport  Narxi
0          poezd      70      poezd  98000
1      avtomobil     180  avtomobil  10000

### Indekslar ustida birlashtirish

In [21]:
A

  Transport_turi Tezligi
0          poezd      70
1      avtomobil     180
2           kema      45

In [22]:
B

   Transport  Narxi
0      poezd  98000
1  avtomobil  10000
2    tramvay  65000

In [26]:
A = A.set_index('Transport_turi')
A

               Tezligi
Transport_turi
poezd               70
avtomobil          180
kema                45

In [27]:
merged1 = pd.merge(A, B, left_index=True, right_on='Transport')
merged1

  Tezligi  Transport  Narxi
0      70      poezd  98000
1     180  avtomobil  10000

In [28]:
B = B.set_index('Transport')
B

           Narxi
Transport
poezd      98000
avtomobil  10000
tramvay    65000

In [29]:
merged2 = pd.merge(A, B, left_index=True, right_index=True)
merged2

               Tezligi  Narxi
Transport_turi
poezd               70  98000
avtomobil          180  10000

### Concatination

In [35]:
bank = pd.read_csv("Practicum_Datasets/bank.csv", delimiter=";")
bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [36]:
bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   str
 2   marital    4521 non-null   str
 3   education  4521 non-null   str
 4   default    4521 non-null   str
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   str
 7   loan       4521 non-null   str
 8   contact    4521 non-null   str
 9   day        4521 non-null   int64
 10  month      4521 non-null   str
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   str
 16  y          4521 non-null   str
dtypes: int64(7), str(10)
memory usage: 600.6 KB

In [37]:
bank1 , bank2 = bank[:2521], bank[2521:]
bank1.shape, bank2.shape

((2521, 17), (2000, 17))

```concat```

In [38]:
pd.concat([bank1, bank2])

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [39]:
bank1, bank2, bank3 = bank[:1681], bank[1681:3362], bank[3362:]
bank1.shape, bank2.shape, bank3.shape

((1681, 17), (1681, 17), (1159, 17))

In [42]:
pd.concat([bank1, bank2, bank3], axis=0)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [43]:
pd.concat([bank1, bank2, bank3], axis=1)

,age,job,marital,education,default,balance,housing,loan,contact,day,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30.0,unemployed,married,primary,no,1787.0,no,no,cellular,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33.0,services,married,secondary,no,4789.0,yes,yes,cellular,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,35.0,management,single,tertiary,no,1350.0,yes,no,cellular,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30.0,management,married,tertiary,no,1476.0,yes,yes,unknown,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,59.0,blue-collar,married,secondary,no,0.0,yes,no,unknown,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,cellular,30.0,jul,329.0,5.0,-1.0,0.0,unknown,no
4517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,unknown,9.0,may,153.0,1.0,-1.0,0.0,unknown,no
4518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,cellular,19.0,aug,151.0,11.0,-1.0,0.0,unknown,no
4519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,cellular,6.0,feb,129.0,4.0,211.0,3.0,other,no
4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,cellular,3.0,apr,345.0,2.0,249.0,7.0,other,no

In [44]:
bank1 = bank1.set_index('age')
bank1

,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
age,,,,,,,,,,,,,,,,
30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,admin.,married,secondary,no,168,yes,no,cellular,7,may,249,2,169,1,failure,no
33,self-employed,married,tertiary,no,263,no,no,cellular,4,may,119,2,-1,0,unknown,no
39,blue-collar,married,secondary,no,-405,yes,no,cellular,8,may,177,1,-1,0,unknown,no
38,self-employed,married,secondary,no,279,yes,no,unknown,28,may,110,5,-1,0,unknown,no
32,technician,single,secondary,no,0,no,no,cellular,18,aug,594,4,-1,0,unknown,yes

In [45]:
bank2 = bank2.set_index('age')
bank2

,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
age,,,,,,,,,,,,,,,,
65,unknown,married,unknown,no,300,no,no,cellular,12,jan,105,1,-1,0,unknown,no
34,unemployed,single,tertiary,no,415,no,no,cellular,12,aug,123,1,-1,0,unknown,no
34,admin.,single,primary,no,0,yes,yes,cellular,6,may,172,4,-1,0,unknown,no
42,blue-collar,single,primary,no,1322,yes,yes,cellular,8,jul,178,1,-1,0,unknown,no
31,services,married,secondary,no,1062,yes,yes,cellular,6,apr,230,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,blue-collar,married,primary,no,25,yes,no,unknown,6,may,266,3,-1,0,unknown,no
35,management,married,tertiary,no,365,no,no,cellular,21,nov,168,2,-1,0,unknown,no
25,unemployed,single,secondary,no,34,no,yes,unknown,4,jul,316,1,-1,0,unknown,no
79,retired,married,primary,no,429,no,no,telephone,8,jul,1006,2,-1,0,unknown,yes
53,technician,married,primary,no,6839,yes,no,cellular,19,nov,77,1,-1,0,unknown,no

In [47]:
pd.concat([bank1, bank2],axis=1)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### Uzun datasetdan Keng dataset olish ```pivot```

In [48]:
data = pd.read_csv("Practicum_Datasets/data_pivot.csv")
data.head()

                            date     item     value
0  1959-03-31 23:59:59.999999999  realgdp  2710.349
1  1959-03-31 23:59:59.999999999     infl     0.000
2  1959-03-31 23:59:59.999999999    unemp     5.800
3  1959-06-30 23:59:59.999999999  realgdp  2778.801
4  1959-06-30 23:59:59.999999999     infl     2.340

In [ ]:
pivoted_data = data.pivot('date', 'item', 'value') #bu eski usul ekan , ishlamas ekan
pivoted_data

TypeError: DataFrame.pivot() takes 1 positional argument but 4 were given

In [53]:
pivoted_data = data.pivot(index='date', columns='item', values='value')
pivoted_data

item                           infl    realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]

In [57]:
data['value2'] = np.random.rand(len(data))
data.head()

                            date     item     value    value2
0  1959-03-31 23:59:59.999999999  realgdp  2710.349  0.011305
1  1959-03-31 23:59:59.999999999     infl     0.000  0.497826
2  1959-03-31 23:59:59.999999999    unemp     5.800  0.786427
3  1959-06-30 23:59:59.999999999  realgdp  2778.801  0.871919
4  1959-06-30 23:59:59.999999999     infl     2.340  0.580396

In [58]:
pivoted_data = data.pivot(index='date', columns='item')
pivoted_data

                              value                     value2            \
item                           infl    realgdp unemp      infl   realgdp
date
1959-03-31 23:59:59.999999999  0.00   2710.349   5.8  0.497826  0.011305
1959-06-30 23:59:59.999999999  2.34   2778.801   5.1  0.580396  0.871919
1959-09-30 23:59:59.999999999  2.74   2775.488   5.3  0.748195  0.905035
1959-12-31 23:59:59.999999999  0.27   2785.204   5.6  0.574558  0.125574
1960-03-31 23:59:59.999999999  2.31   2847.699   5.2  0.539386  0.801639
...                             ...        ...   ...       ...       ...
2008-09-30 23:59:59.999999999 -3.16  13324.600   6.0  0.308962  0.371082
2008-12-31 23:59:59.999999999 -8.79  13141.920   6.9  0.943004  0.968517
2009-03-31 23:59:59.999999999  0.94  12925.410   8.1  0.647372  0.552593
2009-06-30 23:59:59.999999999  3.37  12901.504   9.2  0.416587  0.070023
2009-09-30 23:59:59.999999999  3.56  12990.341   9.6  0.417219  0.597675


item                              unemp
date
1959-03-31 23:59:59.999999999  0.786427
1959-06-30 23:59:59.999999999  0.274571
1959-09-30 23:59:59.999999999  0.008045
1959-12-31 23:59:59.999999999  0.619334
1960-03-31 23:59:59.999999999  0.369140
...                                 ...
2008-09-30 23:59:59.999999999  0.573912
2008-12-31 23:59:59.999999999  0.688979
2009-03-31 23:59:59.999999999  0.974793
2009-06-30 23:59:59.999999999  0.784660
2009-09-30 23:59:59.999999999  0.720336

[203 rows x 6 columns]

In [59]:
pivoted_data['value'].head(10)

item                           infl   realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00  2710.349    5.8
1959-06-30 23:59:59.999999999  2.34  2778.801    5.1
1959-09-30 23:59:59.999999999  2.74  2775.488    5.3
1959-12-31 23:59:59.999999999  0.27  2785.204    5.6
1960-03-31 23:59:59.999999999  2.31  2847.699    5.2
1960-06-30 23:59:59.999999999  0.14  2834.390    5.2
1960-09-30 23:59:59.999999999  2.70  2839.022    5.6
1960-12-31 23:59:59.999999999  1.21  2802.616    6.3
1961-03-31 23:59:59.999999999 -0.40  2819.264    6.8
1961-06-30 23:59:59.999999999  1.47  2872.005    7.0