In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

           pop2021   area
country
Macau      658.394     30
Monaco      39.511      2
Burundi  12255.433  27834
Macau      658.394     30
Monaco      39.511      2

In [3]:
df.loc['Uzbekistan']

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

In [5]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

In [6]:
population = df.pop2021
population

country
Macau                 658.394
Monaco                 39.511
Burundi             12255.433
Macau                 658.394
Monaco                 39.511
                      ...
Namibia              2587.344
Western Sahara        611.875
Mongolia             3329.289
Falkland Islands        3.533
Greenland              56.877
Name: pop2021, Length: 247, dtype: float64

In [7]:
guruh = pd.cut(population, bins)
guruh

country
Macau                    (0, 1000]
Monaco                   (0, 1000]
Burundi             (10000, 30000]
Macau                    (0, 1000]
Monaco                   (0, 1000]
                         ...
Namibia              (1000, 10000]
Western Sahara           (0, 1000]
Mongolia             (1000, 10000]
Falkland Islands         (0, 1000]
Greenland                (0, 1000]
Name: pop2021, Length: 247, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] < (30000, 50000] < (50000, 100000] < (100000, 300000] < (300000, 1500000]]

In [8]:
guruh.value_counts()

pop2021
(0, 1000]            80
(1000, 10000]        73
(10000, 30000]       46
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [9]:
df['guruh'] = guruh

In [10]:
df

                    pop2021     area           guruh
country
Macau               658.394       30       (0, 1000]
Monaco               39.511        2       (0, 1000]
Burundi           12255.433    27834  (10000, 30000]
Macau               658.394       30       (0, 1000]
Monaco               39.511        2       (0, 1000]
...                     ...      ...             ...
Namibia            2587.344   825615   (1000, 10000]
Western Sahara      611.875   266000       (0, 1000]
Mongolia           3329.289  1564110   (1000, 10000]
Falkland Islands      3.533    12173       (0, 1000]
Greenland            56.877  2166086       (0, 1000]

[247 rows x 3 columns]

In [11]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [12]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [13]:
bins = [0, 10000, 20000, 50000]

In [14]:
range = pd.cut(df.price, bins)

In [15]:
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [16]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [17]:
names = ['arzon', 'orta', 'qimmat']

In [ ]:
range = pd.cut(df.price, bins, labels=names)
range

index
0      orta
1      orta
2      orta
3      orta
4      orta
      ...
81    arzon
82    arzon
86    arzon
87     orta
88     orta
Name: price, Length: 61, dtype: category
Categories (3, str): ['arzon' < 'orta' < 'qimmat']

In [19]:
range.value_counts()

price
arzon     28
orta      17
qimmat    13
Name: count, dtype: int64

In [21]:
range = pd.cut(df.price, 3)

range.value_counts()

price
(5110.751, 18567.333]     44
(31983.667, 45400.0]       9
(18567.333, 31983.667]     5
Name: count, dtype: int64

In [ ]:
range = pd.qcut(df.price, 3) #qcut chiqadigan countlarini nisbatan teng qilib ajratarkan
range.value_counts()

price
(5150.999, 7295.0]    20
(7295.0, 16430.0]     19
(16430.0, 45400.0]    19
Name: count, dtype: int64

### groupby() yordamida guruhlash

In [24]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [25]:
df.company.unique()

<StringArray>
[  'alfa-romero',          'audi',           'bmw',     'chevrolet',
         'dodge',         'honda',         'isuzu',        'jaguar',
         'mazda', 'mercedes-benz',    'mitsubishi',        'nissan',
       'porsche',        'toyota',    'volkswagen',         'volvo']
Length: 16, dtype: str

In [26]:
df.company.value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [28]:
df.groupby('company').mean(numeric_only=True)

,wheel-base,length,horsepower,average-mileage,price
company,,,,,
alfa-romero,90.566667,169.600000,125.333333,20.333333,15498.333333
audi,101.200000,180.800000,109.250000,20.000000,16392.500000
bmw,103.433333,185.033333,144.833333,19.000000,27213.333333
chevrolet,92.466667,151.933333,62.666667,41.000000,6007.000000
dodge,93.700000,157.300000,68.000000,31.000000,6303.000000
honda,96.500000,167.200000,92.333333,26.333333,10195.000000
isuzu,94.433333,160.833333,72.666667,33.333333,6785.000000
jaguar,109.333333,196.966667,204.666667,14.333333,34600.000000
mazda,95.900000,164.260000,75.400000,28.000000,9654.800000
mercedes-benz,113.225000,197.275000,153.500000,18.000000,35040.000000
mitsubishi,95.000000,164.850000,78.000000,29.500000,6689.000000
nissan,95.680000,170.140000,82.800000,31.400000,8289.000000
porsche,92.466667,171.166667,234.000000,17.000000,35528.000000
toyota,96.957143,167.571429,75.428571,28.714286,8216.857143
volkswagen,97.300000,171.700000,72.250000,31.750000,8435.000000
volvo,104.300000,188.800000,114.000000,23.000000,13177.500000

In [29]:
df.groupby('company').price.max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [31]:
df.groupby(['company','body-style']).price.mean()

company        body-style
alfa-romero    convertible    14997.500000
               hatchback      16500.000000
audi           sedan          15550.000000
               wagon          18920.000000
bmw            sedan          27213.333333
chevrolet      hatchback       5723.000000
               sedan           6575.000000
dodge          hatchback       6303.000000
honda          sedan          11645.000000
               wagon           7295.000000
isuzu          sedan           6785.000000
jaguar         sedan          34600.000000
mazda          hatchback       7482.500000
               sedan          18344.000000
mercedes-benz  hardtop        45400.000000
               sedan          33256.000000
               wagon          28248.000000
mitsubishi     hatchback       5789.000000
               sedan           7589.000000
nissan         sedan           8524.000000
               wagon           7349.000000
porsche        convertible    37028.000000
               hardtop        34028.000000
               hatchback               NaN
toyota         hatchback       6058.000000
               wagon           9836.000000
volkswagen     sedan           8435.000000
volvo          sedan          12940.000000
               wagon          13415.000000
Name: price, dtype: float64

In [ ]:
df.groupby('company').agg([min, max, np.mean]) # bu eskirgan usul ekan ishlamas ekan

TypeError: Cannot perform reduction 'mean' with string dtype

In [37]:
df.select_dtypes(include='number').groupby(df['company']).agg([min, max, np.mean])

              wheel-base                    length                     \
                     min    max        mean    min    max        mean
company
alfa-romero         88.6   94.5   90.566667  168.8  171.2  169.600000
audi                99.4  105.8  101.200000  176.6  192.7  180.800000
bmw                101.2  110.0  103.433333  176.8  197.0  185.033333
chevrolet           88.4   94.5   92.466667  141.1  158.8  151.933333
dodge               93.7   93.7   93.700000  157.3  157.3  157.300000
honda               96.5   96.5   96.500000  157.1  175.4  167.200000
isuzu               94.3   94.5   94.433333  155.9  170.7  160.833333
jaguar             102.0  113.0  109.333333  191.7  199.6  196.966667
mazda               93.1  104.9   95.900000  159.1  175.0  164.260000
mercedes-benz      110.0  120.9  113.225000  190.9  208.1  197.275000
mitsubishi          93.7   96.3   95.000000  157.3  172.4  164.850000
nissan              94.5  100.4   95.680000  165.3  184.6  170.140000
porsche             89.5   98.4   92.466667  168.9  175.7  171.166667
toyota              95.7  104.5   96.957143  158.7  187.8  167.571429
volkswagen          97.3   97.3   97.300000  171.7  171.7  171.700000
volvo              104.3  104.3  104.300000  188.8  188.8  188.800000

              horsepower                  average-mileage                 \
                     min  max        mean             min max       mean
company
alfa-romero          111  154  125.333333              19  21  20.333333
audi                 102  115  109.250000              18  24  20.000000
bmw                  101  182  144.833333              15  23  19.000000
chevrolet             48   70   62.666667              38  47  41.000000
dodge                 68   68   68.000000              31  31  31.000000
honda                 76  101   92.333333              24  30  26.333333
isuzu                 70   78   72.666667              24  38  33.333333
jaguar               176  262  204.666667              13  15  14.333333
mazda                 68  101   75.400000              17  31  28.000000
mercedes-benz        123  184  153.500000              14  22  18.000000
mitsubishi            68   88   78.000000              25  37  29.500000
nissan                55  152   82.800000              19  45  31.400000
porsche              207  288  234.000000              17  17  17.000000
toyota                62  156   75.428571              19  35  28.714286
volkswagen            52  100   72.250000              26  37  31.750000
volvo                114  114  114.000000              23  23  23.000000

                 price
                   min      max          mean
company
alfa-romero    13495.0  16500.0  15498.333333
audi           13950.0  18920.0  16392.500000
bmw            16430.0  41315.0  27213.333333
chevrolet       5151.0   6575.0   6007.000000
dodge           6229.0   6377.0   6303.000000
honda           7295.0  12945.0  10195.000000
isuzu           6785.0   6785.0   6785.000000
jaguar         32250.0  36000.0  34600.000000
mazda           5195.0  18344.0   9654.800000
mercedes-benz  25552.0  45400.0  35040.000000
mitsubishi      5389.0   8189.0   6689.000000
nissan          6649.0  13499.0   8289.000000
porsche        34028.0  37028.0  35528.000000
toyota          5348.0  15750.0   8216.857143
volkswagen      7775.0   9995.0   8435.000000
volvo          12940.0  13415.0  13177.500000

In [38]:
df.select_dtypes(include='number').groupby(df['company']).agg([min, max, lambda x: np.mean(x)])

              wheel-base                    length                     \
                     min    max  <lambda_0>    min    max  <lambda_0>
company
alfa-romero         88.6   94.5   90.566667  168.8  171.2  169.600000
audi                99.4  105.8  101.200000  176.6  192.7  180.800000
bmw                101.2  110.0  103.433333  176.8  197.0  185.033333
chevrolet           88.4   94.5   92.466667  141.1  158.8  151.933333
dodge               93.7   93.7   93.700000  157.3  157.3  157.300000
honda               96.5   96.5   96.500000  157.1  175.4  167.200000
isuzu               94.3   94.5   94.433333  155.9  170.7  160.833333
jaguar             102.0  113.0  109.333333  191.7  199.6  196.966667
mazda               93.1  104.9   95.900000  159.1  175.0  164.260000
mercedes-benz      110.0  120.9  113.225000  190.9  208.1  197.275000
mitsubishi          93.7   96.3   95.000000  157.3  172.4  164.850000
nissan              94.5  100.4   95.680000  165.3  184.6  170.140000
porsche             89.5   98.4   92.466667  168.9  175.7  171.166667
toyota              95.7  104.5   96.957143  158.7  187.8  167.571429
volkswagen          97.3   97.3   97.300000  171.7  171.7  171.700000
volvo              104.3  104.3  104.300000  188.8  188.8  188.800000

              horsepower                  average-mileage                 \
                     min  max  <lambda_0>             min max <lambda_0>
company
alfa-romero          111  154  125.333333              19  21  20.333333
audi                 102  115  109.250000              18  24  20.000000
bmw                  101  182  144.833333              15  23  19.000000
chevrolet             48   70   62.666667              38  47  41.000000
dodge                 68   68   68.000000              31  31  31.000000
honda                 76  101   92.333333              24  30  26.333333
isuzu                 70   78   72.666667              24  38  33.333333
jaguar               176  262  204.666667              13  15  14.333333
mazda                 68  101   75.400000              17  31  28.000000
mercedes-benz        123  184  153.500000              14  22  18.000000
mitsubishi            68   88   78.000000              25  37  29.500000
nissan                55  152   82.800000              19  45  31.400000
porsche              207  288  234.000000              17  17  17.000000
toyota                62  156   75.428571              19  35  28.714286
volkswagen            52  100   72.250000              26  37  31.750000
volvo                114  114  114.000000              23  23  23.000000

                 price
                   min      max    <lambda_0>
company
alfa-romero    13495.0  16500.0  15498.333333
audi           13950.0  18920.0  16392.500000
bmw            16430.0  41315.0  27213.333333
chevrolet       5151.0   6575.0   6007.000000
dodge           6229.0   6377.0   6303.000000
honda           7295.0  12945.0  10195.000000
isuzu           6785.0   6785.0   6785.000000
jaguar         32250.0  36000.0  34600.000000
mazda           5195.0  18344.0   9654.800000
mercedes-benz  25552.0  45400.0  35040.000000
mitsubishi      5389.0   8189.0   6689.000000
nissan          6649.0  13499.0   8289.000000
porsche        34028.0  37028.0  35528.000000
toyota          5348.0  15750.0   8216.857143
volkswagen      7775.0   9995.0   8435.000000
volvo          12940.0  13415.0  13177.500000