In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

           pop2021   area
country
Macau      658.394     30
Monaco      39.511      2
Burundi  12255.433  27834
Macau      658.394     30
Monaco      39.511      2

In [3]:
df.loc['Uzbekistan']

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

In [5]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

In [6]:
population = df.pop2021
population

country
Macau                 658.394
Monaco                 39.511
Burundi             12255.433
Macau                 658.394
Monaco                 39.511
                      ...
Namibia              2587.344
Western Sahara        611.875
Mongolia             3329.289
Falkland Islands        3.533
Greenland              56.877
Name: pop2021, Length: 247, dtype: float64

In [7]:
guruh = pd.cut(population, bins)
guruh

country
Macau                    (0, 1000]
Monaco                   (0, 1000]
Burundi             (10000, 30000]
Macau                    (0, 1000]
Monaco                   (0, 1000]
                         ...
Namibia              (1000, 10000]
Western Sahara           (0, 1000]
Mongolia             (1000, 10000]
Falkland Islands         (0, 1000]
Greenland                (0, 1000]
Name: pop2021, Length: 247, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] < (30000, 50000] < (50000, 100000] < (100000, 300000] < (300000, 1500000]]

In [8]:
guruh.value_counts()

pop2021
(0, 1000]            80
(1000, 10000]        73
(10000, 30000]       46
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [9]:
df['guruh'] = guruh

In [10]:
df

                    pop2021     area           guruh
country
Macau               658.394       30       (0, 1000]
Monaco               39.511        2       (0, 1000]
Burundi           12255.433    27834  (10000, 30000]
Macau               658.394       30       (0, 1000]
Monaco               39.511        2       (0, 1000]
...                     ...      ...             ...
Namibia            2587.344   825615   (1000, 10000]
Western Sahara      611.875   266000       (0, 1000]
Mongolia           3329.289  1564110   (1000, 10000]
Falkland Islands      3.533    12173       (0, 1000]
Greenland            56.877  2166086       (0, 1000]

[247 rows x 3 columns]

In [11]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [12]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [13]:
bins = [0, 10000, 20000, 50000]

In [14]:
range = pd.cut(df.price, bins)

In [15]:
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [16]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [17]:
names = ['arzon', 'orta', 'qimmat']

In [ ]:
range = pd.cut(df.price, bins, labels=names)
range

index
0      orta
1      orta
2      orta
3      orta
4      orta
      ...
81    arzon
82    arzon
86    arzon
87     orta
88     orta
Name: price, Length: 61, dtype: category
Categories (3, str): ['arzon' < 'orta' < 'qimmat']

In [19]:
range.value_counts()

price
arzon     28
orta      17
qimmat    13
Name: count, dtype: int64

In [21]:
range = pd.cut(df.price, 3)

range.value_counts()

price
(5110.751, 18567.333]     44
(31983.667, 45400.0]       9
(18567.333, 31983.667]     5
Name: count, dtype: int64

In [ ]:
range = pd.qcut(df.price, 3) #qcut chiqadigan countlarini nisbatan teng qilib ajratarkan
range.value_counts()

price
(5150.999, 7295.0]    20
(7295.0, 16430.0]     19
(16430.0, 45400.0]    19
Name: count, dtype: int64