![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 3-MODUL. MA’LUMOTLARGA ISHLOV BERISH

### 3.2 Ma'lumotlarni tozalash va tayyorlash

## Guruhlash
Guruhlashning vazifasi ma'lumotlarni tahlil qilish uchun biror ustun qiymatlarini berilgan oraliqlarga (guruhlarga) tushurib olish.

Misol uchun, sizda foydalanuvchilar haqida ma'lumotlar jamlangan va u yerda har bir foydalanuvchining yoshi ham ko'rsatilgan. Siz foydalanuvchilarni qaysi yosh oralig'ida ekanini (qaysi guruhga tegishli ekanini) ko'rmoqchisiz:

![](https://www.researchgate.net/profile/Gemma-Burgess-5/publication/299603937/figure/fig1/AS:347169551863808@1459783079654/The-age-ranges-of-survey-respondents.png)

Yuqoridagi kabi natijani olish uchun biz foydalanauvchilarni yosihga qarab ma'lum oraliqqa joylashimiz kerak, `pandas` bu jarayonni bir muncha osonlashtiradi.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

           pop2021   area
country
Macau      658.394     30
Monaco      39.511      2
Burundi  12255.433  27834
Macau      658.394     30
Monaco      39.511      2

Takrorlanishlarni o'chirib yuboramiz:

In [3]:
df.drop_duplicates(inplace=True)

In [4]:
df.head()

             pop2021   area
country
Macau        658.394     30
Monaco        39.511      2
Burundi    12255.433  27834
Singapore   5896.686    710
Hong Kong   7552.810   1104

Tartiblab olamiz:

In [5]:
df.sort_index(inplace=True)

In [6]:
df.head()

                  pop2021     area
country
Afghanistan     39835.428   652230
Albania          2872.933    28748
Algeria         44616.624  2381741
American Samoa     55.100      199
Andorra            77.355      468

Keling ba'zi davlatlar aholisini ham chiqarib ko'ramiz:

In [7]:
df.loc['China']

pop2021    1444216.107
area       9706961.000
Name: China, dtype: float64

In [8]:
df.loc['Uzbekistan']

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

Ahamiyat bering, aholi soni minglarda berilgan, bu degani aniq qiymatni topish uchun ko'rsatilgan qiymatni `1000` ga ko'paytirasiz. Ya'ni, O'zbekiston aholisi `33935` ko'rsatilgan, demak aholi soni `33935x1000=33milloin 935ming`

Keling, quyidagi oraliqlarda nechtadan davlat borligini tahlil qilamiz:
- 1 milliongacha (`0-1000`)
- 1-10mln oraqlida (`1000-10000`)
- 10-30mln oraliqda (`10000-30000`)
- 30-50mln oraliqda (`30000-50000`)
- 50-100mln (`50000-10000`)
- 100-300mln (`100000-300000`)
- 300mln-1.5mlrd (`300000-1500000`)

Buning uchun quydagi bin (nuqtalarni) yaratib olamiz:

In [9]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

Aholi sonini ham alohida ajratib olamiz:

In [10]:
population = df.pop2021

In [ ]:
population.head()

country
Afghanistan       39835.428
Albania            2872.933
Algeria           44616.624
American Samoa       55.100
Andorra              77.355
Name: pop2021, dtype: float64

`population` va `bins` ni jamlaymiz:

In [11]:
oraliq = pd.cut(population,bins)

In [12]:
oraliq

country
Afghanistan          (30000, 50000]
Albania               (1000, 10000]
Algeria              (30000, 50000]
American Samoa            (0, 1000]
Andorra                   (0, 1000]
                          ...
Wallis and Futuna         (0, 1000]
Western Sahara            (0, 1000]
Yemen                (30000, 50000]
Zambia               (10000, 30000]
Zimbabwe             (10000, 30000]
Name: pop2021, Length: 232, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

Ko'rib turganingizdek, yangi o'zgaruvchi davlatlar qaysi oraliqqa tushishini ko'rsatayapti.

Oraliqlarni chiqarish uchun `.categories` parametriga murojaat qilamiz:

Oraliqlardagi davlatlar sonini ko'rish uchun `.value_counts()` metodiga muorjaat qilamiz:

In [13]:
oraliq.value_counts()

pop2021
(0, 1000]            72
(1000, 10000]        68
(10000, 30000]       44
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

Istasangiz, `oraliq` obyektini `df` ga ham qo'shib qo'yishingiz mumkin:

In [14]:
df['popBins'] = oraliq

In [15]:
df.head()

                  pop2021     area         popBins
country
Afghanistan     39835.428   652230  (30000, 50000]
Albania          2872.933    28748   (1000, 10000]
Algeria         44616.624  2381741  (30000, 50000]
American Samoa     55.100      199       (0, 1000]
Andorra            77.355      468       (0, 1000]

Yana bir misol ko'ramiz:

In [16]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

Yuqoridagi jadvalda turli avtolarning narxi ko'rsatilgan, keling ularni ham oraliqlarga bo'lamiz. Avval eng arzon va qimmat mashinalarni ajratib olaylik:

In [17]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [18]:
bins = [0, 10000, 20000, 50000]

In [19]:
range = pd.cut(df.price, bins)

In [ ]:
range.value_counts()

(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: price, dtype: int64

Tushunarli bo'lishi uchun biz bu oraliqlarga nom ham berishimiz mumkin:

In [20]:
groups = ["arzon", "o'rta", "qimmat"]
range = pd.cut(df.price, bins, labels=groups)
range.value_counts()

price
arzon     28
o'rta     17
qimmat    13
Name: count, dtype: int64

Yuqorida misollarda biz `bins` nomli o'zgaruvchi yaratib oldik va guruhlarga o'zimiz ajratdik. Agar bu jarayonni avtomatlashtirishni istasangiz, `bins` ro'yxati o'rtniga nechta guruh kerak ekanligini ko'rsatsangiz kifoya:

In [21]:
range = pd.cut(df.price, 3)
range.value_counts()

price
(5110.751, 18567.333]     44
(31983.667, 45400.0]       9
(18567.333, 31983.667]     5
Name: count, dtype: int64

Ko'rib turganingizdek, yuqorida biz qiymatlarni 3 ta guruhga ajratishni so'radik va biznkidan farqli natijani oldik.

In [22]:
range = pd.cut(df.price, 4)
range.value_counts()

price
(5110.751, 15213.25]    36
(15213.25, 25275.5]     10
(35337.75, 45400.0]      7
(25275.5, 35337.75]      5
Name: count, dtype: int64

Agar sizga qiymatlarni teng a'zolardan iborat guruhga ajratish talab qilinsa, `.qcut()` metodiga murojaat qilasiz:

In [23]:
range = pd.qcut(df.price, 3)
range.value_counts()

price
(16430.0, 45400.0]    20
(5150.999, 7295.0]    19
(7295.0, 16430.0]     19
Name: count, dtype: int64

In [24]:
range = pd.qcut(df.horsepower, 3)
range.value_counts()

horsepower
(47.999, 70.0]    24
(111.0, 288.0]    20
(70.0, 111.0]     17
Name: count, dtype: int64