In [1]:
import datetime as dt

In [2]:
hozir  = dt.datetime.now()
print(hozir)

2026-04-30 11:52:32.674700

In [3]:
type(hozir)

datetime.datetime

In [4]:
hozir.hour

11

In [5]:
hozir.minute

52

In [6]:
hozir.weekday()

3

In [7]:
hozir.month

4

In [9]:
import pandas as pd
df = pd.read_csv("database.csv")
df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  str
 1   Time                        23412 non-null  str
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  str
 5   Depth                       23412 non-null  float64
 6   Depth Error                 4461 non-null   float64
 7   Depth Seismic Stations      7097 non-null   float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  str
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7299 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17352 non-null  float64
 16  ID                          23412 non-null  str
 17  Source                      23412 non-null  str
 18  Location Source             23412 non-null  str
 19  Magnitude Source            23412 non-null  str
 20  Status                      23412 non-null  str
dtypes: float64(12), str(9)
memory usage: 3.8 MB

In [12]:
sana = df.at[0, 'Date']

In [13]:
sana

'01/02/1965'

In [14]:
pd.to_datetime(df['Date'], format='%m/%d/%Y')

ValueError: time data "1975-02-23T02:58:41.000Z" doesn't match format "%m/%d/%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [15]:
df['Date'].str.len()

0        10
1        10
2        10
3        10
4        10
         ..
23407    10
23408    10
23409    10
23410    10
23411    10
Name: Date, Length: 23412, dtype: int64

In [16]:
df['Date'].str.len().value_counts()

Date
10    23409
24        3
Name: count, dtype: int64

In [17]:
df[df['Date'].str.len() == 24]

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
3378,1975-02-23T02:58:41.000Z,1975-02-23T02:58:41.000Z,8.017,124.075,Earthquake,623.0,NaN,NaN,5.6,MB,...,NaN,NaN,NaN,NaN,NaN,USP0000A09,US,US,US,Reviewed
7512,1985-04-28T02:53:41.530Z,1985-04-28T02:53:41.530Z,-32.998,-71.766,Earthquake,33.0,NaN,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,1.30,USP0002E81,US,US,HRV,Reviewed
20650,2011-03-13T02:23:34.520Z,2011-03-13T02:23:34.520Z,36.344,142.344,Earthquake,10.1,13.9,289.0,5.8,MWC,...,NaN,32.3,NaN,NaN,1.06,USP000HWQP,US,US,GCMT,Reviewed

In [18]:
df.loc[3378, 'Date'] = "02/23/1975"
df.loc[7512, 'Date'] = "04/28/1985"
df.loc[20650, 'Date'] = "03/13/2011"

In [19]:
df[df['Date'].str.len() == 24]

Empty DataFrame
Columns: [Date, Time, Latitude, Longitude, Type, Depth, Depth Error, Depth Seismic Stations, Magnitude, Magnitude Type, Magnitude Error, Magnitude Seismic Stations, Azimuthal Gap, Horizontal Distance, Horizontal Error, Root Mean Square, ID, Source, Location Source, Magnitude Source, Status]
Index: []

[0 rows x 21 columns]

In [20]:
pd.to_datetime(df['Date'], format='%m/%d/%Y')

0       1965-01-02
1       1965-01-04
2       1965-01-05
3       1965-01-08
4       1965-01-09
           ...
23407   2016-12-28
23408   2016-12-28
23409   2016-12-28
23410   2016-12-29
23411   2016-12-30
Name: Date, Length: 23412, dtype: datetime64[us]

In [21]:
df['datetime'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')
df

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-02
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-04
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-05
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-08
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed,2016-12-28
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed,2016-12-28
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed,2016-12-28
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed,2016-12-29
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed,2016-12-30

In [22]:
df.at[0, 'datetime'].month

1

In [25]:
df['datetime'].dt.month

0         1
1         1
2         1
3         1
4         1
         ..
23407    12
23408    12
23409    12
23410    12
23411    12
Name: datetime, Length: 23412, dtype: int32

In [26]:
df['month'] = df['datetime'].dt.month

In [27]:
df['month'].value_counts()

month
3     2114
8     2014
12    2001
11    1987
9     1985
4     1971
5     1964
10    1952
1     1891
7     1880
2     1829
6     1824
Name: count, dtype: int64

In [28]:
df['weekday'] = df['datetime'].dt.weekday

In [29]:
df['weekday'].value_counts()

weekday
5    3433
2    3431
4    3362
0    3349
3    3306
6    3287
1    3244
Name: count, dtype: int64

In [30]:
df['time'] = pd.to_datetime(df['Time'], format='%H:%M:%S')

ValueError: time data "1975-02-23T02:58:41.000Z" doesn't match format "%H:%M:%S". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [41]:
df['Time'].str.len()

0        8
1        8
2        8
3        8
4        8
        ..
23407    8
23408    8
23409    8
23410    8
23411    8
Name: Time, Length: 23412, dtype: int64

In [42]:
df['Time'].str.len().value_counts()

Time
8     23409
24        3
Name: count, dtype: int64

In [43]:
df[df['Time'].str.len() != 8]

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime,month,weekday
3378,02/23/1975,1975-02-23T02:58:41.000Z,8.017,124.075,Earthquake,623.0,NaN,NaN,5.6,MB,...,NaN,NaN,USP0000A09,US,US,US,Reviewed,1975-02-23,2,6
7512,04/28/1985,1985-04-28T02:53:41.530Z,-32.998,-71.766,Earthquake,33.0,NaN,NaN,5.6,MW,...,NaN,1.30,USP0002E81,US,US,HRV,Reviewed,1985-04-28,4,6
20650,03/13/2011,2011-03-13T02:23:34.520Z,36.344,142.344,Earthquake,10.1,13.9,289.0,5.8,MWC,...,NaN,1.06,USP000HWQP,US,US,GCMT,Reviewed,2011-03-13,3,6

In [44]:
df.loc[3378, 'Time'] = '02:58:41'

In [45]:
df.loc[7512, 'Time'] = '02:53:41'
df.loc[20650, 'Time'] = '02:23:34'

In [46]:
df['time'] = pd.to_datetime(df['Time'], format='%H:%M:%S')

In [47]:
df['time']

0       1900-01-01 13:44:18
1       1900-01-01 11:29:49
2       1900-01-01 18:05:58
3       1900-01-01 18:49:43
4       1900-01-01 13:32:50
                ...
23407   1900-01-01 08:22:12
23408   1900-01-01 09:13:47
23409   1900-01-01 12:38:51
23410   1900-01-01 22:30:19
23411   1900-01-01 20:08:28
Name: time, Length: 23412, dtype: datetime64[us]

In [48]:
df

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime,month,weekday,time
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,...,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-02,1,5,1900-01-01 13:44:18
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,...,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-04,1,0,1900-01-01 11:29:49
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,...,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-05,1,1,1900-01-01 18:05:58
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-08,1,4,1900-01-01 18:49:43
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-09,1,5,1900-01-01 13:32:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,0.1898,NN00570710,NN,NN,NN,Reviewed,2016-12-28,12,2,1900-01-01 08:22:12
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,0.2187,NN00570744,NN,NN,NN,Reviewed,2016-12-28,12,2,1900-01-01 09:13:47
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,1.5200,US10007NAF,US,US,US,Reviewed,2016-12-28,12,2,1900-01-01 12:38:51
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,1.4300,US10007NL0,US,US,US,Reviewed,2016-12-29,12,3,1900-01-01 22:30:19
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,0.9100,US10007NTD,US,US,US,Reviewed,2016-12-30,12,4,1900-01-01 20:08:28