![Imgur](https://i.imgur.com/h4PPC71.png)
#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [159]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [160]:
#javobni shu yerda yozing
df.drop('Unnamed: 0', axis=1, inplace=True)
df.columns = [col.lower().replace(' ', '_') for col in df.columns]
df

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash
...,...,...,...,...,...,...,...,...,...
17529,ORD_320102,CUST_021,Drinks,NaN,-1.0,4.0,4.0,2023-12-23,Cash
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3.0,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4.0,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2.0,8.0,2022-01-27,Digital Wallet
17533,ORD_680707,CUST_006,Desserts,NaN,7.0,4.0,28.0,2023-01-07,NaN

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [161]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17498 non-null  object
 3   item            15776 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17104 non-null  float64
 6   order_total     17104 non-null  float64
 7   order_date      17534 non-null  object
 8   payment_method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [162]:
df.describe()

              price      quantity   order_total
count  17534.000000  17104.000000  17104.000000
mean       6.207312      3.014149     19.914494
std        4.993782      1.414598     18.732549
min       -1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [163]:
#javobni shu yerda yozing
df.isnull().sum()

order_id             0
customer_id          0
category            36
item              1758
price                0
quantity           430
order_total        430
order_date           0
payment_method    1082
dtype: int64

In [164]:
df['category']= df['category'].fillna('Unknown')
df.isnull().sum()

order_id             0
customer_id          0
category             0
item              1758
price                0
quantity           430
order_total        430
order_date           0
payment_method    1082
dtype: int64

In [165]:
df.item = df.item.fillna("Unknown")
df.isnull().sum()

order_id             0
customer_id          0
category             0
item                 0
price                0
quantity           430
order_total        430
order_date           0
payment_method    1082
dtype: int64

In [166]:
df.quantity = df.quantity.fillna(df.quantity.median())
df.isnull().sum()

order_id             0
customer_id          0
category             0
item                 0
price                0
quantity             0
order_total        430
order_date           0
payment_method    1082
dtype: int64

In [167]:
df.order_total = df.order_total.fillna(df.quantity * df.price)
df.isnull().sum()

order_id             0
customer_id          0
category             0
item                 0
price                0
quantity             0
order_total          0
order_date           0
payment_method    1082
dtype: int64

In [168]:
mode_payment = df.payment_method.mode()[0]
df.payment_method = df.payment_method.fillna(mode_payment)
df.isnull().sum()

order_id          0
customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [169]:
#javobni shu yerda yozing
df.duplicated().sum()

np.int64(0)

In [170]:
df[df.duplicated(keep=False)].sort_values(by='order_id')

Empty DataFrame
Columns: [order_id, customer_id, category, item, price, quantity, order_total, order_date, payment_method]
Index: []

In [171]:
id_duplicates = df['order_id'].duplicated().sum()
id_duplicates

np.int64(0)

In [172]:

text_columns = ['category', 'item', 'payment_method']

for col in text_columns:
    df[col] = df[col].astype(str).str.lower().str.strip()

print(f"Tozalashdan keyingi to'liq dublikatlar: {df.duplicated().sum()}")

Tozalashdan keyingi to'liq dublikatlar: 0

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [173]:
df.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad#?,3.0,1.0,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3.0,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4.0,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,-1.0,2.0,5.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4.0,48.0,2022-05-15,cash

In [174]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17534 non-null  object
 3   item            17534 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17534 non-null  float64
 6   order_total     17534 non-null  float64
 7   order_date      17534 non-null  object
 8   payment_method  17534 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [175]:
df.describe()

              price      quantity   order_total
count  17534.000000  17534.000000  17534.000000
mean       6.207312      3.013802     19.352544
std        4.993782      1.397145     18.837835
min       -1.000000      1.000000     -3.000000
25%        3.000000      2.000000      7.000000
50%        5.000000      3.000000     14.000000
75%        7.000000      4.000000     24.000000
max       20.000000      5.000000    100.000000

In [176]:
df.price = df.price.mask(df.price <= 0, df.price.median())
df.order_total = df.order_total.mask(df.order_total <= 0, df.order_total.median())
df.describe()

              price      quantity   order_total
count  17534.000000  17534.000000  17534.000000
mean       6.507072      3.013802     19.769448
std        4.724985      1.397145     18.524016
min        1.000000      1.000000      1.000000
25%        4.000000      2.000000      8.000000
50%        5.000000      3.000000     14.000000
75%        7.000000      4.000000     24.000000
max       20.000000      5.000000    100.000000

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [177]:
#javobni shu yerda yozing
for col in ['category', 'item', 'payment_method']:
    df[col] = df[col].astype(str).str.lower().str.strip()
df.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad#?,3.0,1.0,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3.0,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4.0,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,5.0,2.0,5.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4.0,48.0,2022-05-15,cash

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [178]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17534 non-null  object
 3   item            17534 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17534 non-null  float64
 6   order_total     17534 non-null  float64
 7   order_date      17534 non-null  object
 8   payment_method  17534 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [179]:
df['order_id'] = df['order_id'].str.replace('ORD_', '', regex=False).astype('Int64')
df['customer_id'] = df['customer_id'].str.replace('CUST_', '', regex=False).astype('Int64')
df['order_date'] = pd.to_datetime(df['order_date'])
df['quantity'] = df['quantity'].astype('int64')
df['category'] = df['category'].astype('category')
df['payment_method'] = df['payment_method'].astype('category')
df.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,705844,92,unknown,side salad#?,3.0,1,3.0,2023-12-21,credit card
1,338528,21,side dishes,mashed potatoes,4.0,3,12.0,2023-05-19,digital wallet
2,443849,29,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card
3,630508,75,drinks,unknown,5.0,2,5.0,2022-08-09,credit card
4,648269,31,main dishes,pasta alfredo,12.0,4,48.0,2022-05-15,cash

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [180]:
#javobni shu yerda yozing
# Faqat harf va raqam bo'lmagan belgilarni o'z ichiga olgan nomlarni ko'rish
import re
pattern = r'[^a-zA-Z0-9\s]' # Harf, son va bo'shliqdan boshqa hamma narsa
strange_items = df[df['item'].str.contains(pattern, na=False)]['item'].unique()
print(strange_items)

['side salad#?' 'water (0.5)' 'grilled vegetables?' 'nachos grande#'
 'grilled chicken?' 'chicken melt#' 'lemonade (1.0)' 'grilled chicken#'
 'coca cola?' 'steak#' 'orange juice#' 'french fries?' 'side salad?'
 'french fries#' 'nachos grande?' 'brownie#' 'chocolate cake#'
 'pasta alfredo#' 'chicken melt?' 'ice cream#' 'sweet potato fries?'
 'iced tea?' 'vegetarian platter?' 'water#' 'cheese fries?'
 'grilled vegetables#' 'beef chili#' 'side salad#' 'mashed potatoes?'
 'orange juice?' 'iced tea#?' 'pasta alfredo?' 'coca cola#' 'fruit salad?'
 'brownie?' 'salmon#' 'steak?' 'beef chili?' 'water?' 'cheese fries#'
 'lemonade?' 'cheesecake?' 'chocolate cake?' 'ice cream?'
 'grilled vegetables#?' 'vegetarian platter#' 'fruit salad#'
 'sweet potato fries#' 'onion rings#' 'iced tea#' 'mashed potatoes#'
 'brownie#?' 'salmon?' 'beef chili#?' 'garlic bread?' 'lemonade#?'
 'garlic bread#' 'onion rings?' 'chocolate cake#?' 'pasta alfredo#?'
 'cheesecake#' 'mashed potatoes#?']

In [181]:
df['item'] = df['item'].str.replace(r'[#?]', '', regex=True).str.strip()

In [182]:
df['item'].str.lower().unique()

array(['side salad', 'mashed potatoes', 'grilled chicken', 'unknown',
       'pasta alfredo', 'salmon', 'garlic bread', 'vegetarian platter',
       'brownie', 'sweet potato fries', 'lemonade', 'orange juice',
       'chocolate cake', 'coca cola', 'grilled vegetables',
       'cheese fries', 'beef chili', 'chicken melt', 'fruit salad',
       'french fries', 'ice cream', 'cheesecake', 'iced tea',
       'water (0.5)', 'nachos grande', 'water', 'onion rings', 'steak',
       'lemonade (1.0)'], dtype=object)

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [183]:
#javobni shu yerda yozing
df.price = df.price.mask(df.price <= 0, df.price.median())
df.price.value_counts()

price
5.0     4097
4.0     2673
3.0     2180
6.0     1337
2.5     1144
12.0    1059
1.0     1022
7.0      998
15.0     866
20.0     597
8.0      466
18.0     445
14.0     403
10.0     247
Name: count, dtype: int64

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [184]:
#javobni shu yerda yozing
df.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,705844,92,unknown,side salad,3.0,1,3.0,2023-12-21,credit card
1,338528,21,side dishes,mashed potatoes,4.0,3,12.0,2023-05-19,digital wallet
2,443849,29,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card
3,630508,75,drinks,unknown,5.0,2,5.0,2022-08-09,credit card
4,648269,31,main dishes,pasta alfredo,12.0,4,48.0,2022-05-15,cash

In [185]:
# Avval 'unknown' qiymatlarni NaN ga qaytaramiz (fillna ishlashi uchun)
import numpy as np
df['category'] = df['category'].replace('unknown', np.nan)

# Mahsulot nomi (item) bo'yicha kategoriyalarni guruhlab to'ldiramiz
df['category'] = df['category'].fillna(df.groupby('item')['category'].transform('first'))
df.category.value_counts()

/tmp/ipykernel_981/183355956.py:3: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['category'] = df['category'].replace('unknown', np.nan)

category
main dishes    3550
starters       3525
desserts       3496
drinks         3492
side dishes    3471
Name: count, dtype: int64

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [186]:
#javobni shu yerda yozing
df['item'] = df['item'].str.replace(r'\s+', ' ', regex=True)
df['item'] = df['item'].str.lower().str.strip()
sorted(df['item'].unique())

['beef chili',
 'brownie',
 'cheese fries',
 'cheesecake',
 'chicken melt',
 'chocolate cake',
 'coca cola',
 'french fries',
 'fruit salad',
 'garlic bread',
 'grilled chicken',
 'grilled vegetables',
 'ice cream',
 'iced tea',
 'lemonade',
 'lemonade (1.0)',
 'mashed potatoes',
 'nachos grande',
 'onion rings',
 'orange juice',
 'pasta alfredo',
 'salmon',
 'side salad',
 'steak',
 'sweet potato fries',
 'unknown',
 'vegetarian platter',
 'water',
 'water (0.5)']

In [187]:
df.item.value_counts().sort_index()

item
beef chili             470
brownie                469
cheese fries           686
cheesecake             485
chicken melt           442
chocolate cake         798
coca cola              756
french fries           897
fruit salad            449
garlic bread           399
grilled chicken        822
grilled vegetables     578
ice cream              936
iced tea               328
lemonade               473
lemonade (1.0)           6
mashed potatoes        799
nachos grande          238
onion rings            373
orange juice           591
pasta alfredo          998
salmon                 422
side salad             978
steak                  574
sweet potato fries     471
unknown               1758
vegetarian platter     382
water                   54
water (0.5)            902
Name: count, dtype: int64

In [188]:
df = df[df['item'] != 'unknown']
df.item.value_counts().sort_index()

item
beef chili            470
brownie               469
cheese fries          686
cheesecake            485
chicken melt          442
chocolate cake        798
coca cola             756
french fries          897
fruit salad           449
garlic bread          399
grilled chicken       822
grilled vegetables    578
ice cream             936
iced tea              328
lemonade              473
lemonade (1.0)          6
mashed potatoes       799
nachos grande         238
onion rings           373
orange juice          591
pasta alfredo         998
salmon                422
side salad            978
steak                 574
sweet potato fries    471
vegetarian platter    382
water                  54
water (0.5)           902
Name: count, dtype: int64

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [189]:
#javobni shu yerda yozing
duplicate_rows = df.duplicated().sum()
if duplicate_rows > 0:
    df = df.drop_duplicates()

In [190]:
unique_customers = df['customer_id'].nunique()
unique_customers

100

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [191]:
#javobni shu yerda yozing
df['item'] = df['item'].str.replace(r'\(.*\)', '', regex=True).str.strip()
df['item'].str.lower().unique()

/tmp/ipykernel_981/1480952289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['item'] = df['item'].str.replace(r'\(.*\)', '', regex=True).str.strip()

array(['side salad', 'mashed potatoes', 'grilled chicken',
       'pasta alfredo', 'salmon', 'garlic bread', 'vegetarian platter',
       'brownie', 'sweet potato fries', 'lemonade', 'orange juice',
       'chocolate cake', 'coca cola', 'grilled vegetables',
       'cheese fries', 'beef chili', 'chicken melt', 'fruit salad',
       'french fries', 'ice cream', 'cheesecake', 'iced tea', 'water',
       'nachos grande', 'onion rings', 'steak'], dtype=object)

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [202]:
#javobni shu yerda yozing
df['item'].value_counts().head(5)

item
pasta alfredo    998
side salad       978
water            956
ice cream        936
french fries     897
Name: count, dtype: int64

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [203]:
#javobni shu yerda yozing
df.groupby('customer_id')['order_total'].sum().mean()

np.float64(3146.815)

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [205]:
#javobni shu yerda yozing
df['weekday'] = df['order_date'].dt.day_name()
df.weekday.value_counts()

/tmp/ipykernel_981/1992611299.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weekday'] = df['order_date'].dt.day_name()

weekday
Monday       2278
Friday       2276
Thursday     2275
Saturday     2255
Sunday       2244
Tuesday      2227
Wednesday    2221
Name: count, dtype: int64

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [211]:
#javobni shu yerda yozing
mean_price = df['price'].mean()
df[df['price'] > 2 * mean_price]

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method,weekday
2,443849,29,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card,Wednesday
5,381680,31,main dishes,salmon,18.0,5,90.0,2022-07-20,digital wallet,Wednesday
9,743636,85,main dishes,vegetarian platter,14.0,5,70.0,2022-08-07,credit card,Sunday
11,726419,25,main dishes,salmon,18.0,5,90.0,2023-10-30,cash,Monday
12,754176,47,main dishes,salmon,18.0,1,18.0,2023-04-11,cash,Tuesday
...,...,...,...,...,...,...,...,...,...,...
17434,196563,98,main dishes,grilled chicken,15.0,5,75.0,2023-05-20,digital wallet,Saturday
17453,591820,82,main dishes,salmon,18.0,3,54.0,2023-12-08,credit card,Friday
17480,771570,93,main dishes,salmon,18.0,2,36.0,2023-03-24,credit card,Friday
17490,900549,47,main dishes,salmon,18.0,2,36.0,2023-04-25,digital wallet,Tuesday
17495,872487,17,main dishes,steak,20.0,5,100.0,2023-11-01,credit card,Wednesday

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [213]:
#javobni shu yerda yozing
df.groupby('category')['quantity'].sum().sort_values(ascending=False)

/tmp/ipykernel_981/3395662875.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('category')['quantity'].sum().sort_values(ascending=False)

category
main dishes    9730
starters       9684
desserts       9449
drinks         9387
side dishes    9324
Name: quantity, dtype: int64

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [214]:
#javobni shu yerda yozing
df.groupby("customer_id")['quantity'].mean()

customer_id
1      2.974843
2      3.126582
3      2.979167
4      3.125000
5      2.930556
         ...
96     3.000000
97     3.041420
98     3.036364
99     2.953642
100    2.910615
Name: quantity, Length: 100, dtype: float64

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [198]:
#javobni shu yerda yozing



# 1. Kategoriya omili

# 2. Hafta kuni (Vaqt) omili

# 3. Narx va Miqdor balansi

# 4. To'lov usullari