In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('merc.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/merc.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [4]:
pd.read_excel('uzbekistan.xlsx')

                       Boʻlinishi  Maydoni (kv.km)  Aholisi
0                Andijon viloyati             4200  1899000
1                 Buxoro viloyati            39400  1384700
2               Fargʻona viloyati             6800  2597000
3                 Jizzax viloyati            20500   910500
4                 Xorazm viloyati             6300  1200000
5               Namangan viloyati             7900  1862000
6                 Navoiy viloyati           110800   767500
7            Qashqadaryo viloyati            28400  2029000
8   Qoraqalpogʻiston Respublikasi           160000  1200000
9              Samarqand viloyati            16400  2322000
10              Sirdaryo viloyati             5100   648100
11           Surxondaryo viloyati            20800  1676000
12              Toshkent viloyati            15300  4450000

In [5]:
pd.read_excel('uzbekistan.xlsx', index_col=0)

                               Maydoni (kv.km)  Aholisi
Boʻlinishi
Andijon viloyati                          4200  1899000
Buxoro viloyati                          39400  1384700
Fargʻona viloyati                         6800  2597000
Jizzax viloyati                          20500   910500
Xorazm viloyati                           6300  1200000
Namangan viloyati                         7900  1862000
Navoiy viloyati                         110800   767500
Qashqadaryo viloyati                     28400  2029000
Qoraqalpogʻiston Respublikasi           160000  1200000
Samarqand viloyati                       16400  2322000
Sirdaryo viloyati                         5100   648100
Surxondaryo viloyati                     20800  1676000
Toshkent viloyati                        15300  4450000

In [6]:
pd.read_excel('uzbekistan.xlsx', index_col=0 , names=['hudud', 'maydon', 'aholi'])

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [7]:
pd.read_csv('automobile_data.csv',sep=',',index_col='index', nrows=15)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250
6,audi,wagon,105.8,192.7,ohc,five,110,19,18920
9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430
10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970
13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760
14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315
15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880
16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151
17,chevrolet,hatchback,94.5,155.9,ohc,four,70,38,6295

In [8]:
df = pd.read_excel('uzbekistan.xlsx', index_col=0 , names=['hudud', 'maydon', 'aholi'])
df

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [9]:
df.to_csv('new_uzb.csv')

In [10]:
obj = df.maydon
obj

hudud
Andijon viloyati                   4200
Buxoro viloyati                   39400
Fargʻona viloyati                  6800
Jizzax viloyati                   20500
Xorazm viloyati                    6300
Namangan viloyati                  7900
Navoiy viloyati                  110800
Qashqadaryo viloyati              28400
Qoraqalpogʻiston Respublikasi    160000
Samarqand viloyati                16400
Sirdaryo viloyati                  5100
Surxondaryo viloyati              20800
Toshkent viloyati                 15300
Name: maydon, dtype: int64

In [11]:
obj.to_csv('objmaydon.csv')

In [12]:
pd.read_csv('objmaydon.csv')

                            hudud  maydon
0                Andijon viloyati    4200
1                 Buxoro viloyati   39400
2               Fargʻona viloyati    6800
3                 Jizzax viloyati   20500
4                 Xorazm viloyati    6300
5               Namangan viloyati    7900
6                 Navoiy viloyati  110800
7            Qashqadaryo viloyati   28400
8   Qoraqalpogʻiston Respublikasi  160000
9              Samarqand viloyati   16400
10              Sirdaryo viloyati    5100
11           Surxondaryo viloyati   20800
12              Toshkent viloyati   15300

In [13]:
pd.read_csv('objmaydon.csv', index_col='hudud').squeeze()

hudud
Andijon viloyati                   4200
Buxoro viloyati                   39400
Fargʻona viloyati                  6800
Jizzax viloyati                   20500
Xorazm viloyati                    6300
Namangan viloyati                  7900
Navoiy viloyati                  110800
Qashqadaryo viloyati              28400
Qoraqalpogʻiston Respublikasi    160000
Samarqand viloyati                16400
Sirdaryo viloyati                  5100
Surxondaryo viloyati              20800
Toshkent viloyati                 15300
Name: maydon, dtype: int64

In [14]:
df2  = pd.read_csv('automobile_data.csv', index_col=0)
df2

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [15]:
df2.to_excel('newcars.xlsx', index=False, columns=['company', 'body-style', 'price'])

In [16]:
pd.read_excel('newcars.xlsx')

        company   body-style    price
0   alfa-romero  convertible  13495.0
1   alfa-romero  convertible  16500.0
2   alfa-romero    hatchback  16500.0
3          audi        sedan  13950.0
4          audi        sedan  17450.0
..          ...          ...      ...
56   volkswagen        sedan   7975.0
57   volkswagen        sedan   7995.0
58   volkswagen        sedan   9995.0
59        volvo        sedan  12940.0
60        volvo        wagon  13415.0

[61 rows x 3 columns]

### ```HDF5``` format

In [17]:
hdf5obj = pd.HDFStore('data.h5')

In [18]:
hdf5obj.put("uzdata", df)

In [19]:
hdf5obj.put('cardata', df2)

In [20]:
hdf5obj.keys()

['/cardata', '/uzdata']

In [21]:
hdf5obj['uzdata']

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [22]:
hdf5obj.close() # yopish kerak ekan, yopilgan holatda ichidagilarni ham ko'ra olmas ekanmiz

In [23]:
hdf5obj= pd.HDFStore('data.h5') # qaytadan ochish uchun

In [24]:
hdf5obj['cardata']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [25]:
hdf5obj.close()

In [26]:
data = pd.read_hdf('data.h5', key='uzdata')
data

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [27]:
data.to_hdf("data.h5", key='uzdata')

### Web sahifalar

In [28]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# bazi websaytlar pandasdan yuborilgan so'rovlar uchun javob bermas ekan , bu agent niqob bo'lsa keyin berarkan

tashkent = pd.read_html('https://en.wikipedia.org/wiki/Tashkent', storage_options=headers)
tashkent[6]

,0,1,2
0,Historical population,Historical population,NaN
1,"YearPop.±% p.a.1897 155,673— 1959 911,930+2.89...","YearPop.±% p.a.2007 2,157,100+0.77%2008 2,180,...",NaN
2,Year,Pop.,±% p.a.
3,1897,155673,—
4,1959,911930,+2.89%
5,1970,1384509,+3.87%
6,1979,1780002,+2.83%
7,1983,1902000,+1.67%
8,1989,2072459,+1.44%
9,1991,2130200,+1.38%
10,1995,2097400,−0.39%
11,2000,2142300,+0.42%
12,2001,2137900,−0.21%
13,2002,2136600,−0.06%
14,2003,2139200,+0.12%
15,2004,2135400,−0.18%
16,2005,2135700,+0.01%
17,2006,2140600,+0.23%
18,Year,Pop.,±% p.a.
19,2007,2157100,+0.77%
20,2008,2180000,+1.06%
21,2009,2206300,+1.21%
22,2010,2234300,+1.27%
23,2011,2296500,+2.78%
24,2012,2309300,+0.56%
25,2013,2340900,+1.37%
26,2014,2352900,+0.51%
27,2015,2371300,+0.78%
28,2016,2393200,+0.92%
29,2017,2424100,+1.29%
30,2018,2464900,+1.68%
31,2019,2509900,+1.83%
32,2020,2571700,+2.46%
33,2021,2694400,+4.77%
34,Source: Uzbekistan State Statistics Committee[...,Source: Uzbekistan State Statistics Committee[...,NaN

### ```JSON```

In [30]:
df = pd.read_json('comments.json')
df

                                            comments
0  {'id': 1, 'post_id': 101, 'user_id': 5, 'autho...
1  {'id': 2, 'post_id': 101, 'user_id': 8, 'autho...
2  {'id': 3, 'post_id': 102, 'user_id': 3, 'autho...
3  {'id': 4, 'post_id': 101, 'user_id': 12, 'auth...
4  {'id': 5, 'post_id': 103, 'user_id': 7, 'autho...
5  {'id': 6, 'post_id': 102, 'user_id': 15, 'auth...
6  {'id': 7, 'post_id': 104, 'user_id': 2, 'autho...
7  {'id': 8, 'post_id': 103, 'user_id': 9, 'autho...
8  {'id': 9, 'post_id': 104, 'user_id': 11, 'auth...
9  {'id': 10, 'post_id': 105, 'user_id': 4, 'auth...

In [42]:
df_new = pd.DataFrame(df['comments'].tolist())
df_new.drop(['id'],axis=1)

,post_id,user_id,author,content,created,likes,replies
0,101,5,Alice Brown,Great article! Very informative and well-written.,2024-01-10T14:30:00Z,24,3
1,101,8,Bob Wilson,"I disagree with some points, but overall a goo...",2024-01-10T15:45:00Z,8,1
2,102,3,Charlie Davis,This helped me solve my problem. Thanks!,2024-01-11T09:15:00Z,45,0
3,101,12,Diana Miller,Can you elaborate more on the third point?,2024-01-10T16:20:00Z,5,2
4,103,7,Edward Lee,First! Great content as always.,2024-01-12T08:00:00Z,2,0
5,102,15,Fiona Garcia,I've been looking for this information everywh...,2024-01-11T11:30:00Z,32,1
6,104,2,George Kim,The code examples are really helpful.,2024-01-13T10:45:00Z,18,0
7,103,9,Hannah White,Would love to see a follow-up on this topic.,2024-01-12T14:00:00Z,15,1
8,104,11,Ivan Chen,"There's a typo in paragraph 2, just FYI.",2024-01-13T12:30:00Z,3,1
9,105,4,Julia Adams,Bookmarked for later. Looks comprehensive!,2024-01-14T09:00:00Z,11,0